import { AdverbIdentifyTask, AdjAdvTransformTask } from '../types';

export const adverbIdentifyDB: AdverbIdentifyTask[] = [
  // CE2: 12 entrées (id 1-12)
  { id: 1, level: 'CE2', words: [
    { word: 'vite', isAdverb: true },
    { word: 'maison', isAdverb: false },
    { word: 'souvent', isAdverb: true },
    { word: 'chien', isAdverb: false },
    { word: 'bien', isAdverb: true },
    { word: 'rouge', isAdverb: false },
  ]},
  { id: 2, level: 'CE2', words: [
    { word: 'jamais', isAdverb: true },
    { word: 'manger', isAdverb: false },
    { word: 'toujours', isAdverb: true },
    { word: 'livre', isAdverb: false },
    { word: 'très', isAdverb: true },
    { word: 'beau', isAdverb: false },
  ]},
  { id: 3, level: 'CE2', words: [
    { word: 'ici', isAdverb: true },
    { word: 'table', isAdverb: false },
    { word: 'là', isAdverb: true },
    { word: 'courir', isAdverb: false },
    { word: 'trop', isAdverb: true },
    { word: 'petit', isAdverb: false },
  ]},
  { id: 4, level: 'CE2', words: [
    { word: 'dehors', isAdverb: true },
    { word: 'porte', isAdverb: false },
    { word: 'dedans', isAdverb: true },
    { word: 'fleur', isAdverb: false },
    { word: 'maintenant', isAdverb: true },
    { word: 'marcher', isAdverb: false },
  ]},
  { id: 5, level: 'CE2', words: [
    { word: 'hier', isAdverb: true },
    { word: 'demain', isAdverb: true },
    { word: 'soleil', isAdverb: false },
    { word: 'encore', isAdverb: true },
    { word: 'chanter', isAdverb: false },
    { word: 'grand', isAdverb: false },
  ]},
  { id: 6, level: 'CE2', words: [
    { word: 'mal', isAdverb: true },
    { word: 'assez', isAdverb: true },
    { word: 'pain', isAdverb: false },
    { word: 'dormir', isAdverb: false },
    { word: 'partout', isAdverb: true },
    { word: 'ami', isAdverb: false },
  ]},
  { id: 7, level: 'CE2', words: [
    { word: 'lentement', isAdverb: true },
    { word: 'voiture', isAdverb: false },
    { word: 'heureux', isAdverb: false },
    { word: 'doucement', isAdverb: true },
    { word: 'sauter', isAdverb: false },
    { word: 'rapidement', isAdverb: true },
  ]},
  { id: 8, level: 'CE2', words: [
    { word: 'vraiment', isAdverb: true },
    { word: 'forêt', isAdverb: false },
    { word: 'seulement', isAdverb: true },
    { word: 'bleu', isAdverb: false },
    { word: 'rire', isAdverb: false },
    { word: 'tranquillement', isAdverb: true },
  ]},
  { id: 9, level: 'CE2', words: [
    { word: 'joyeusement', isAdverb: true },
    { word: 'chat', isAdverb: false },
    { word: 'facilement', isAdverb: true },
    { word: 'jouer', isAdverb: false },
    { word: 'nuit', isAdverb: false },
    { word: 'tristement', isAdverb: true },
  ]},
  { id: 10, level: 'CE2', words: [
    { word: 'souvent', isAdverb: true },
    { word: 'écrire', isAdverb: false },
    { word: 'jamais', isAdverb: true },
    { word: 'couleur', isAdverb: false },
    { word: 'bien', isAdverb: true },
    { word: 'mauvais', isAdverb: false },
  ]},
  { id: 11, level: 'CE2', words: [
    { word: 'parfois', isAdverb: true },
    { word: 'maison', isAdverb: false },
    { word: 'toujours', isAdverb: true },
    { word: 'maman', isAdverb: false },
    { word: 'beaucoup', isAdverb: true },
    { word: 'danser', isAdverb: false },
  ]},
  { id: 12, level: 'CE2', words: [
    { word: 'vite', isAdverb: true },
    { word: 'beau', isAdverb: false },
    { word: 'trop', isAdverb: true },
    { word: 'école', isAdverb: false },
    { word: 'clairement', isAdverb: true },
    { word: 'cheval', isAdverb: false },
  ]},
  // CM1: 10 entrées (id 13-22)
  { id: 13, level: 'CM1', words: [
    { word: 'silencieusement', isAdverb: true },
    { word: 'branche', isAdverb: false },
    { word: 'probablement', isAdverb: true },
    { word: 'fort', isAdverb: false },
    { word: 'soigneusement', isAdverb: true },
    { word: 'fenêtre', isAdverb: false },
  ]},
  { id: 14, level: 'CM1', words: [
    { word: 'heureusement', isAdverb: true },
    { word: 'jardin', isAdverb: false },
    { word: 'certainement', isAdverb: true },
    { word: 'boire', isAdverb: false },
    { word: 'courageusement', isAdverb: true },
    { word: 'feuille', isAdverb: false },
  ]},
  { id: 15, level: 'CM1', words: [
    { word: 'malheureusement', isAdverb: true },
    { word: 'printemps', isAdverb: false },
    { word: 'doucement', isAdverb: true },
    { word: 'lire', isAdverb: false },
    { word: 'montagne', isAdverb: false },
    { word: 'soudainement', isAdverb: true },
  ]},
  { id: 16, level: 'CM1', words: [
    { word: 'poliment', isAdverb: true },
    { word: 'rivière', isAdverb: false },
    { word: 'brusquement', isAdverb: true },
    { word: 'saison', isAdverb: false },
    { word: 'profondément', isAdverb: true },
    { word: 'oiseau', isAdverb: false },
  ]},
  { id: 17, level: 'CM1', words: [
    { word: 'gentiment', isAdverb: true },
    { word: 'chapitre', isAdverb: false },
    { word: 'gravement', isAdverb: true },
    { word: 'dormir', isAdverb: false },
    { word: 'vivement', isAdverb: true },
    { word: 'nuage', isAdverb: false },
  ]},
  { id: 18, level: 'CM1', words: [
    { word: 'rarement', isAdverb: true },
    { word: 'chemin', isAdverb: false },
    { word: 'brièvement', isAdverb: true },
    { word: 'médecin', isAdverb: false },
    { word: 'prudemment', isAdverb: true },
    { word: 'hiver', isAdverb: false },
  ]},
  { id: 19, level: 'CM1', words: [
    { word: 'librement', isAdverb: true },
    { word: 'planète', isAdverb: false },
    { word: 'honnêtement', isAdverb: true },
    { word: 'étoile', isAdverb: false },
    { word: 'fièrement', isAdverb: true },
    { word: 'aventure', isAdverb: false },
  ]},
  { id: 20, level: 'CM1', words: [
    { word: 'naturellement', isAdverb: true },
    { word: 'forêt', isAdverb: false },
    { word: 'simplement', isAdverb: true },
    { word: 'animal', isAdverb: false },
    { word: 'complètement', isAdverb: true },
    { word: 'ville', isAdverb: false },
  ]},
  { id: 21, level: 'CM1', words: [
    { word: 'rapidement', isAdverb: true },
    { word: 'fleur', isAdverb: false },
    { word: 'exactement', isAdverb: true },
    { word: 'carnet', isAdverb: false },
    { word: 'magnifiquement', isAdverb: true },
    { word: 'voyage', isAdverb: false },
  ]},
  { id: 22, level: 'CM1', words: [
    { word: 'immédiatement', isAdverb: true },
    { word: 'solitude', isAdverb: false },
    { word: 'sincèrement', isAdverb: true },
    { word: 'ciel', isAdverb: false },
    { word: 'abondamment', isAdverb: true },
    { word: 'escalier', isAdverb: false },
  ]},
  // CM2: 10 entrées (id 23-32)
  { id: 23, level: 'CM2', words: [
    { word: 'manifestement', isAdverb: true },
    { word: 'bourgeon', isAdverb: false },
    { word: 'évidemment', isAdverb: true },
    { word: 'sentiment', isAdverb: false },
    { word: 'merveilleusement', isAdverb: true },
    { word: 'carrefour', isAdverb: false },
  ]},
  { id: 24, level: 'CM2', words: [
    { word: 'notamment', isAdverb: true },
    { word: 'territoire', isAdverb: false },
    { word: 'visiblement', isAdverb: true },
    { word: 'légume', isAdverb: false },
    { word: 'continuellement', isAdverb: true },
    { word: 'bureau', isAdverb: false },
  ]},
  { id: 25, level: 'CM2', words: [
    { word: 'particulièrement', isAdverb: true },
    { word: 'paysage', isAdverb: false },
    { word: 'apparemment', isAdverb: true },
    { word: 'courage', isAdverb: false },
    { word: 'finalement', isAdverb: true },
    { word: 'journal', isAdverb: false },
  ]},
  { id: 26, level: 'CM2', words: [
    { word: 'vraisemblablement', isAdverb: true },
    { word: 'découverte', isAdverb: false },
    { word: 'incessamment', isAdverb: true },
    { word: 'lecture', isAdverb: false },
    { word: 'modestement', isAdverb: true },
    { word: 'construction', isAdverb: false },
  ]},
  { id: 27, level: 'CM2', words: [
    { word: 'efficacement', isAdverb: true },
    { word: 'promenade', isAdverb: false },
    { word: 'abruptement', isAdverb: true },
    { word: 'histoire', isAdverb: false },
    { word: 'considérablement', isAdverb: true },
    { word: 'marché', isAdverb: false },
  ]},
  { id: 28, level: 'CM2', words: [
    { word: 'distinctement', isAdverb: true },
    { word: 'lumière', isAdverb: false },
    { word: 'négligemment', isAdverb: true },
    { word: 'famille', isAdverb: false },
    { word: 'impatiemment', isAdverb: true },
    { word: 'rivière', isAdverb: false },
  ]},
  { id: 29, level: 'CM2', words: [
    { word: 'délibérément', isAdverb: true },
    { word: 'monument', isAdverb: false },
    { word: 'précisément', isAdverb: true },
    { word: 'brouillard', isAdverb: false },
    { word: 'respectueusement', isAdverb: true },
    { word: 'sculpture', isAdverb: false },
  ]},
  { id: 30, level: 'CM2', words: [
    { word: 'fréquemment', isAdverb: true },
    { word: 'tristesse', isAdverb: false },
    { word: 'suffisamment', isAdverb: true },
    { word: 'tableau', isAdverb: false },
    { word: 'premièrement', isAdverb: true },
    { word: 'couloir', isAdverb: false },
  ]},
  { id: 31, level: 'CM2', words: [
    { word: 'récemment', isAdverb: true },
    { word: 'village', isAdverb: false },
    { word: 'couramment', isAdverb: true },
    { word: 'musique', isAdverb: false },
    { word: 'logiquement', isAdverb: true },
    { word: 'balcon', isAdverb: false },
  ]},
  { id: 32, level: 'CM2', words: [
    { word: 'clairement', isAdverb: true },
    { word: 'forteresse', isAdverb: false },
    { word: 'aveuglément', isAdverb: true },
    { word: 'culture', isAdverb: false },
    { word: 'adroitement', isAdverb: true },
    { word: 'tableau', isAdverb: false },
  ]},
];

export const adjToAdvDB: AdjAdvTransformTask[] = [
  // CE2: 12 entrées
  { id: 1, level: 'CE2', from: 'vite', to: 'vite', hint: 'Adverbe invariable' },
  { id: 2, level: 'CE2', from: 'rapide', to: 'rapidement', hint: 'adjectif terminé par voyelle → + ment' },
  { id: 3, level: 'CE2', from: 'facile', to: 'facilement', hint: 'adjectif terminé par voyelle → + ment' },
  { id: 4, level: 'CE2', from: 'libre', to: 'librement', hint: 'adjectif terminé par voyelle → + ment' },
  { id: 5, level: 'CE2', from: 'rare', to: 'rarement', hint: 'adjectif terminé par voyelle → + ment' },
  { id: 6, level: 'CE2', from: 'vrai', to: 'vraiment', hint: 'adjectif terminé par voyelle → + ment' },
  { id: 7, level: 'CE2', from: 'poli', to: 'poliment', hint: 'adjectif terminé par voyelle → + ment' },
  { id: 8, level: 'CE2', from: 'lent', to: 'lentement', hint: 'adjectif féminin (lente) → lente + ment' },
  { id: 9, level: 'CE2', from: 'fort', to: 'fortement', hint: 'adjectif féminin (forte) → forte + ment' },
  { id: 10, level: 'CE2', from: 'triste', to: 'tristement', hint: 'adjectif terminé par voyelle → + ment' },
  { id: 11, level: 'CE2', from: 'bon', to: 'bien', hint: 'Cas particulier : bon → bien' },
  { id: 12, level: 'CE2', from: 'mauvais', to: 'mal', hint: 'Cas particulier : mauvais → mal' },
  // CM1: 10 entrées
  { id: 13, level: 'CM1', from: 'joyeux', to: 'joyeusement', hint: 'adjectif en -eux → féminin (joyeuse) + ment' },
  { id: 14, level: 'CM1', from: 'heureux', to: 'heureusement', hint: 'adjectif en -eux → féminin (heureuse) + ment' },
  { id: 15, level: 'CM1', from: 'doux', to: 'doucement', hint: 'adjectif en -oux → féminin (douce) + ment' },
  { id: 16, level: 'CM1', from: 'grand', to: 'grandement', hint: 'adjectif féminin (grande) → grande + ment' },
  { id: 17, level: 'CM1', from: 'gentil', to: 'gentiment', hint: 'Cas particulier : gentil → gentiment' },
  { id: 18, level: 'CM1', from: 'léger', to: 'légèrement', hint: 'adjectif féminin (légère) → légère + ment' },
  { id: 19, level: 'CM1', from: 'fier', to: 'fièrement', hint: 'adjectif féminin (fière) → fière + ment' },
  { id: 20, level: 'CM1', from: 'calme', to: 'calmement', hint: 'adjectif terminé par voyelle → + ment' },
  { id: 21, level: 'CM1', from: 'simple', to: 'simplement', hint: 'adjectif terminé par voyelle → + ment' },
  { id: 22, level: 'CM1', from: 'naturel', to: 'naturellement', hint: 'adjectif féminin (naturelle) → naturelle + ment' },
  // CM2: 10 entrées
  { id: 23, level: 'CM2', from: 'bref', to: 'brièvement', hint: 'Cas particulier : bref → brièvement' },
  { id: 24, level: 'CM2', from: 'silencieux', to: 'silencieusement', hint: 'adjectif en -eux → féminin (silencieuse) + ment' },
  { id: 25, level: 'CM2', from: 'courageux', to: 'courageusement', hint: 'adjectif en -eux → féminin (courageuse) + ment' },
  { id: 26, level: 'CM2', from: 'prudent', to: 'prudemment', hint: 'adjectif en -ent → remplacer par -emment' },
  { id: 27, level: 'CM2', from: 'évident', to: 'évidemment', hint: 'adjectif en -ent → remplacer par -emment' },
  { id: 28, level: 'CM2', from: 'fréquent', to: 'fréquemment', hint: 'adjectif en -ent → remplacer par -emment' },
  { id: 29, level: 'CM2', from: 'suffisant', to: 'suffisamment', hint: 'adjectif en -ant → remplacer par -amment' },
  { id: 30, level: 'CM2', from: 'abondant', to: 'abondamment', hint: 'adjectif en -ant → remplacer par -amment' },
  { id: 31, level: 'CM2', from: 'négligent', to: 'négligemment', hint: 'adjectif en -ent → remplacer par -emment' },
  { id: 32, level: 'CM2', from: 'récent', to: 'récemment', hint: 'adjectif en -ent → remplacer par -emment' },
];

export const advToAdjDB: AdjAdvTransformTask[] = [
  // CE2: 12 entrées
  { id: 1, level: 'CE2', from: 'rapidement', to: 'rapide' },
  { id: 2, level: 'CE2', from: 'facilement', to: 'facile' },
  { id: 3, level: 'CE2', from: 'librement', to: 'libre' },
  { id: 4, level: 'CE2', from: 'rarement', to: 'rare' },
  { id: 5, level: 'CE2', from: 'vraiment', to: 'vrai' },
  { id: 6, level: 'CE2', from: 'poliment', to: 'poli' },
  { id: 7, level: 'CE2', from: 'lentement', to: 'lent' },
  { id: 8, level: 'CE2', from: 'fortement', to: 'fort' },
  { id: 9, level: 'CE2', from: 'tristement', to: 'triste' },
  { id: 10, level: 'CE2', from: 'bien', to: 'bon' },
  { id: 11, level: 'CE2', from: 'mal', to: 'mauvais' },
  { id: 12, level: 'CE2', from: 'calmement', to: 'calme' },
  // CM1: 10 entrées
  { id: 13, level: 'CM1', from: 'joyeusement', to: 'joyeux' },
  { id: 14, level: 'CM1', from: 'heureusement', to: 'heureux' },
  { id: 15, level: 'CM1', from: 'doucement', to: 'doux' },
  { id: 16, level: 'CM1', from: 'grandement', to: 'grand' },
  { id: 17, level: 'CM1', from: 'gentiment', to: 'gentil' },
  { id: 18, level: 'CM1', from: 'légèrement', to: 'léger' },
  { id: 19, level: 'CM1', from: 'fièrement', to: 'fier' },
  { id: 20, level: 'CM1', from: 'simplement', to: 'simple' },
  { id: 21, level: 'CM1', from: 'naturellement', to: 'naturel' },
  { id: 22, level: 'CM1', from: 'clairement', to: 'clair' },
  // CM2: 10 entrées
  { id: 23, level: 'CM2', from: 'brièvement', to: 'bref' },
  { id: 24, level: 'CM2', from: 'silencieusement', to: 'silencieux' },
  { id: 25, level: 'CM2', from: 'courageusement', to: 'courageux' },
  { id: 26, level: 'CM2', from: 'prudemment', to: 'prudent' },
  { id: 27, level: 'CM2', from: 'évidemment', to: 'évident' },
  { id: 28, level: 'CM2', from: 'fréquemment', to: 'fréquent' },
  { id: 29, level: 'CM2', from: 'suffisamment', to: 'suffisant' },
  { id: 30, level: 'CM2', from: 'abondamment', to: 'abondant' },
  { id: 31, level: 'CM2', from: 'négligemment', to: 'négligent' },
  { id: 32, level: 'CM2', from: 'récemment', to: 'récent' },
];
