import { DetIdentifyTask, DetGenderTask, DetNumberTask, DetWriteTask, DetChooseTask, DetArticleSortTask } from '../types';

export const DET_IDENTIFY_DATABASE: DetIdentifyTask[] = [
  { id: 1, level: 'CE1', words: [{ text: 'le', isDeterminer: true }, { text: 'chat', isDeterminer: false }, { text: 'courir', isDeterminer: false }, { text: 'une', isDeterminer: true }, { text: 'maison', isDeterminer: false }, { text: 'joli', isDeterminer: false }, { text: 'mon', isDeterminer: true }, { text: 'chien', isDeterminer: false }] },
  { id: 2, level: 'CE1', words: [{ text: 'la', isDeterminer: true }, { text: 'fleur', isDeterminer: false }, { text: 'rouge', isDeterminer: false }, { text: 'des', isDeterminer: true }, { text: 'oiseaux', isDeterminer: false }, { text: 'voler', isDeterminer: false }, { text: 'ma', isDeterminer: true }, { text: 'sœur', isDeterminer: false }] },
  { id: 3, level: 'CE1', words: [{ text: 'les', isDeterminer: true }, { text: 'enfants', isDeterminer: false }, { text: 'jouer', isDeterminer: false }, { text: 'beau', isDeterminer: false }, { text: 'ce', isDeterminer: true }, { text: 'livre', isDeterminer: false }, { text: 'lire', isDeterminer: false }, { text: 'son', isDeterminer: true }] },
  { id: 4, level: 'CE1', words: [{ text: 'un', isDeterminer: true }, { text: 'arbre', isDeterminer: false }, { text: 'grand', isDeterminer: false }, { text: 'cette', isDeterminer: true }, { text: 'école', isDeterminer: false }, { text: 'apprendre', isDeterminer: false }, { text: 'ta', isDeterminer: true }, { text: 'mère', isDeterminer: false }] },
  { id: 5, level: 'CE1', words: [{ text: 'mes', isDeterminer: true }, { text: 'amis', isDeterminer: false }, { text: 'rire', isDeterminer: false }, { text: 'notre', isDeterminer: true }, { text: 'jardin', isDeterminer: false }, { text: 'vert', isDeterminer: false }, { text: 'sauter', isDeterminer: false }, { text: 'balle', isDeterminer: false }] },
  { id: 6, level: 'CE1', words: [{ text: 'votre', isDeterminer: true }, { text: 'maîtresse', isDeterminer: false }, { text: 'leur', isDeterminer: true }, { text: 'maison', isDeterminer: false }, { text: 'courir', isDeterminer: false }, { text: 'petit', isDeterminer: false }, { text: 'chanter', isDeterminer: false }, { text: 'soleil', isDeterminer: false }] },
  { id: 7, level: 'CE1', words: [{ text: 'ses', isDeterminer: true }, { text: 'jouets', isDeterminer: false }, { text: 'tes', isDeterminer: true }, { text: 'cahiers', isDeterminer: false }, { text: 'écrire', isDeterminer: false }, { text: 'rouge', isDeterminer: false }, { text: 'cheval', isDeterminer: false }, { text: 'manger', isDeterminer: false }] },
  { id: 8, level: 'CE1', words: [{ text: 'ces', isDeterminer: true }, { text: 'pommes', isDeterminer: false }, { text: 'nos', isDeterminer: true }, { text: 'voisins', isDeterminer: false }, { text: 'dormir', isDeterminer: false }, { text: 'bleu', isDeterminer: false }, { text: 'nuage', isDeterminer: false }, { text: 'vite', isDeterminer: false }] },
  { id: 9, level: 'CE1', words: [{ text: 'vos', isDeterminer: true }, { text: 'parents', isDeterminer: false }, { text: 'leurs', isDeterminer: true }, { text: 'enfants', isDeterminer: false }, { text: 'danser', isDeterminer: false }, { text: 'fort', isDeterminer: false }, { text: 'montagne', isDeterminer: false }, { text: 'grimper', isDeterminer: false }] },
  { id: 10, level: 'CE1', words: [{ text: 'l\'', isDeterminer: true }, { text: 'ami', isDeterminer: false }, { text: 'gentil', isDeterminer: false }, { text: 'une', isDeterminer: true }, { text: 'table', isDeterminer: false }, { text: 'boire', isDeterminer: false }, { text: 'ton', isDeterminer: true }, { text: 'frère', isDeterminer: false }] },
  { id: 11, level: 'CE1', words: [{ text: 'sa', isDeterminer: true }, { text: 'voiture', isDeterminer: false }, { text: 'rapide', isDeterminer: false }, { text: 'le', isDeterminer: true }, { text: 'soleil', isDeterminer: false }, { text: 'briller', isDeterminer: false }, { text: 'chaud', isDeterminer: false }, { text: 'ciel', isDeterminer: false }] },
  { id: 12, level: 'CE1', words: [{ text: 'des', isDeterminer: true }, { text: 'fleurs', isDeterminer: false }, { text: 'pousser', isDeterminer: false }, { text: 'joli', isDeterminer: false }, { text: 'mon', isDeterminer: true }, { text: 'vélo', isDeterminer: false }, { text: 'rouler', isDeterminer: false }, { text: 'vite', isDeterminer: false }] },
  { id: 13, level: 'CE1', words: [{ text: 'la', isDeterminer: true }, { text: 'mer', isDeterminer: false }, { text: 'bleu', isDeterminer: false }, { text: 'nager', isDeterminer: false }, { text: 'ces', isDeterminer: true }, { text: 'poissons', isDeterminer: false }, { text: 'beau', isDeterminer: false }, { text: 'plonger', isDeterminer: false }] },
  { id: 14, level: 'CE1', words: [{ text: 'ma', isDeterminer: true }, { text: 'chambre', isDeterminer: false }, { text: 'rangée', isDeterminer: false }, { text: 'les', isDeterminer: true }, { text: 'étoiles', isDeterminer: false }, { text: 'briller', isDeterminer: false }, { text: 'nuit', isDeterminer: false }, { text: 'sombre', isDeterminer: false }] },
  { id: 15, level: 'CE1', words: [{ text: 'un', isDeterminer: true }, { text: 'chaton', isDeterminer: false }, { text: 'mignon', isDeterminer: false }, { text: 'ta', isDeterminer: true }, { text: 'grand-mère', isDeterminer: false }, { text: 'tricoter', isDeterminer: false }, { text: 'doux', isDeterminer: false }, { text: 'laine', isDeterminer: false }] },
];

export const DET_GENDER_DATABASE: DetGenderTask[] = [
  { id: 1, level: 'CE1', phrase: 'un cheval', gender: 'masculin' },
  { id: 2, level: 'CE1', phrase: 'une table', gender: 'féminin' },
  { id: 3, level: 'CE1', phrase: 'le livre', gender: 'masculin' },
  { id: 4, level: 'CE1', phrase: 'la maison', gender: 'féminin' },
  { id: 5, level: 'CE1', phrase: 'mon chien', gender: 'masculin' },
  { id: 6, level: 'CE1', phrase: 'ma fleur', gender: 'féminin' },
  { id: 7, level: 'CE1', phrase: 'son ami', gender: 'masculin' },
  { id: 8, level: 'CE1', phrase: 'sa sœur', gender: 'féminin' },
  { id: 9, level: 'CE1', phrase: 'ce garçon', gender: 'masculin' },
  { id: 10, level: 'CE1', phrase: 'cette fille', gender: 'féminin' },
  { id: 11, level: 'CE1', phrase: 'ton père', gender: 'masculin' },
  { id: 12, level: 'CE1', phrase: 'ta mère', gender: 'féminin' },
  { id: 13, level: 'CE1', phrase: 'notre école', gender: 'féminin' },
  { id: 14, level: 'CE1', phrase: 'notre jardin', gender: 'masculin' },
  { id: 15, level: 'CE1', phrase: 'leur chat', gender: 'masculin' },
  { id: 16, level: 'CE1', phrase: 'leur voiture', gender: 'féminin' },
  { id: 17, level: 'CE1', phrase: 'un oiseau', gender: 'masculin' },
  { id: 18, level: 'CE1', phrase: 'une étoile', gender: 'féminin' },
  { id: 19, level: 'CE1', phrase: 'le soleil', gender: 'masculin' },
  { id: 20, level: 'CE1', phrase: 'la lune', gender: 'féminin' },
];

export const DET_NUMBER_DATABASE: DetNumberTask[] = [
  { id: 1, level: 'CE1', phrase: 'les chevaux', number: 'pluriel' },
  { id: 2, level: 'CE1', phrase: 'une table', number: 'singulier' },
  { id: 3, level: 'CE1', phrase: 'des livres', number: 'pluriel' },
  { id: 4, level: 'CE1', phrase: 'le chat', number: 'singulier' },
  { id: 5, level: 'CE1', phrase: 'mes amis', number: 'pluriel' },
  { id: 6, level: 'CE1', phrase: 'notre école', number: 'singulier' },
  { id: 7, level: 'CE1', phrase: 'ces oiseaux', number: 'pluriel' },
  { id: 8, level: 'CE1', phrase: 'mon chien', number: 'singulier' },
  { id: 9, level: 'CE1', phrase: 'ses jouets', number: 'pluriel' },
  { id: 10, level: 'CE1', phrase: 'la maison', number: 'singulier' },
  { id: 11, level: 'CE1', phrase: 'nos voisins', number: 'pluriel' },
  { id: 12, level: 'CE1', phrase: 'un arbre', number: 'singulier' },
  { id: 13, level: 'CE1', phrase: 'tes cahiers', number: 'pluriel' },
  { id: 14, level: 'CE1', phrase: 'cette fleur', number: 'singulier' },
  { id: 15, level: 'CE1', phrase: 'leurs enfants', number: 'pluriel' },
  { id: 16, level: 'CE1', phrase: 'ton père', number: 'singulier' },
  { id: 17, level: 'CE1', phrase: 'des étoiles', number: 'pluriel' },
  { id: 18, level: 'CE1', phrase: 'votre maison', number: 'singulier' },
  { id: 19, level: 'CE1', phrase: 'vos parents', number: 'pluriel' },
  { id: 20, level: 'CE1', phrase: 'ce garçon', number: 'singulier' },
];

export const DET_WRITE_DATABASE: DetWriteTask[] = [
  { id: 1, level: 'CE1', noun: 'chat', hint: 'masculin singulier', accepted: ['le', 'un', 'mon', 'ton', 'son', 'ce', 'notre', 'votre', 'leur'] },
  { id: 2, level: 'CE1', noun: 'maison', hint: 'féminin singulier', accepted: ['la', 'une', 'ma', 'ta', 'sa', 'cette', 'notre', 'votre', 'leur'] },
  { id: 3, level: 'CE1', noun: 'enfants', hint: 'pluriel', accepted: ['les', 'des', 'mes', 'tes', 'ses', 'nos', 'vos', 'leurs', 'ces'] },
  { id: 4, level: 'CE1', noun: 'arbre', hint: 'masculin singulier', accepted: ['le', 'un', 'cet', 'mon', 'ton', 'son', 'notre', 'votre', 'leur'] },
  { id: 5, level: 'CE1', noun: 'fleur', hint: 'féminin singulier', accepted: ['la', 'une', 'ma', 'ta', 'sa', 'cette', 'notre', 'votre', 'leur'] },
  { id: 6, level: 'CE1', noun: 'livres', hint: 'pluriel', accepted: ['les', 'des', 'mes', 'tes', 'ses', 'nos', 'vos', 'leurs', 'ces'] },
  { id: 7, level: 'CE1', noun: 'cheval', hint: 'masculin singulier', accepted: ['le', 'un', 'mon', 'ton', 'son', 'ce', 'notre', 'votre', 'leur'] },
  { id: 8, level: 'CE1', noun: 'école', hint: 'féminin singulier', accepted: ['l\'', 'une', 'mon', 'ton', 'son', 'cette', 'notre', 'votre', 'leur'] },
  { id: 9, level: 'CE1', noun: 'oiseaux', hint: 'pluriel', accepted: ['les', 'des', 'mes', 'tes', 'ses', 'nos', 'vos', 'leurs', 'ces'] },
  { id: 10, level: 'CE1', noun: 'soleil', hint: 'masculin singulier', accepted: ['le', 'un', 'mon', 'ton', 'son', 'ce', 'notre', 'votre', 'leur'] },
  { id: 11, level: 'CE1', noun: 'étoile', hint: 'féminin singulier', accepted: ['l\'', 'une', 'ma', 'ta', 'sa', 'cette', 'notre', 'votre', 'leur'] },
  { id: 12, level: 'CE1', noun: 'chiens', hint: 'pluriel', accepted: ['les', 'des', 'mes', 'tes', 'ses', 'nos', 'vos', 'leurs', 'ces'] },
  { id: 13, level: 'CE1', noun: 'garçon', hint: 'masculin singulier', accepted: ['le', 'un', 'mon', 'ton', 'son', 'ce', 'notre', 'votre', 'leur'] },
  { id: 14, level: 'CE1', noun: 'fille', hint: 'féminin singulier', accepted: ['la', 'une', 'ma', 'ta', 'sa', 'cette', 'notre', 'votre', 'leur'] },
  { id: 15, level: 'CE1', noun: 'tables', hint: 'pluriel', accepted: ['les', 'des', 'mes', 'tes', 'ses', 'nos', 'vos', 'leurs', 'ces'] },
  { id: 16, level: 'CE1', noun: 'ami', hint: 'masculin singulier', accepted: ['l\'', 'un', 'mon', 'ton', 'son', 'notre', 'votre', 'leur'] },
  { id: 17, level: 'CE1', noun: 'voiture', hint: 'féminin singulier', accepted: ['la', 'une', 'ma', 'ta', 'sa', 'cette', 'notre', 'votre', 'leur'] },
  { id: 18, level: 'CE1', noun: 'amis', hint: 'pluriel', accepted: ['les', 'des', 'mes', 'tes', 'ses', 'nos', 'vos', 'leurs', 'ces'] },
  { id: 19, level: 'CE1', noun: 'jardin', hint: 'masculin singulier', accepted: ['le', 'un', 'mon', 'ton', 'son', 'ce', 'notre', 'votre', 'leur'] },
  { id: 20, level: 'CE1', noun: 'chambre', hint: 'féminin singulier', accepted: ['la', 'une', 'ma', 'ta', 'sa', 'cette', 'notre', 'votre', 'leur'] },
];

export const DET_CHOOSE_DATABASE: DetChooseTask[] = [
  { id: 1, level: 'CE1', noun: 'chat', options: ['le', 'mon', 'ton', 'la', 'une'], correct: ['le', 'mon', 'ton'] },
  { id: 2, level: 'CE1', noun: 'maison', options: ['la', 'une', 'le', 'ma', 'un'], correct: ['la', 'une', 'ma'] },
  { id: 3, level: 'CE1', noun: 'livres', options: ['les', 'des', 'mes', 'la', 'une'], correct: ['les', 'des', 'mes'] },
  { id: 4, level: 'CE1', noun: 'ami', options: ['un', 'mon', 'ma', 'son', 'une'], correct: ['un', 'mon', 'son'] },
  { id: 5, level: 'CE1', noun: 'fleur', options: ['la', 'une', 'le', 'ta', 'un'], correct: ['la', 'une', 'ta'] },
  { id: 6, level: 'CE1', noun: 'enfants', options: ['les', 'des', 'mes', 'le', 'une'], correct: ['les', 'des', 'mes'] },
  { id: 7, level: 'CE1', noun: 'jardin', options: ['le', 'un', 'notre', 'la', 'une'], correct: ['le', 'un', 'notre'] },
  { id: 8, level: 'CE1', noun: 'école', options: ['notre', 'ma', 'le', 'votre', 'un'], correct: ['notre', 'ma', 'votre'] },
  { id: 9, level: 'CE1', noun: 'cheval', options: ['mon', 'son', 'une', 'leur', 'la'], correct: ['mon', 'son', 'leur'] },
  { id: 10, level: 'CE1', noun: 'étoiles', options: ['les', 'des', 'ses', 'le', 'la'], correct: ['les', 'des', 'ses'] },
  { id: 11, level: 'CE1', noun: 'voiture', options: ['la', 'sa', 'le', 'leur', 'un'], correct: ['la', 'sa', 'leur'] },
  { id: 12, level: 'CE1', noun: 'soleil', options: ['le', 'ce', 'la', 'un', 'une'], correct: ['le', 'ce', 'un'] },
  { id: 13, level: 'CE1', noun: 'fille', options: ['cette', 'la', 'une', 'le', 'mon'], correct: ['cette', 'la', 'une'] },
  { id: 14, level: 'CE1', noun: 'garçon', options: ['ce', 'mon', 'ma', 'ton', 'un'], correct: ['ce', 'mon', 'ton', 'un'] },
  { id: 15, level: 'CE1', noun: 'jouets', options: ['mes', 'tes', 'ses', 'mon', 'le'], correct: ['mes', 'tes', 'ses'] },
  { id: 16, level: 'CE1', noun: 'cahier', options: ['mon', 'ton', 'ma', 'le', 'un'], correct: ['mon', 'ton', 'le', 'un'] },
  { id: 17, level: 'CE1', noun: 'chambre', options: ['ma', 'ta', 'sa', 'mon', 'les'], correct: ['ma', 'ta', 'sa'] },
  { id: 18, level: 'CE1', noun: 'arbres', options: ['les', 'ces', 'nos', 'la', 'une'], correct: ['les', 'ces', 'nos'] },
  { id: 19, level: 'CE1', noun: 'lune', options: ['la', 'une', 'le', 'ma', 'mon'], correct: ['la', 'une', 'ma'] },
  { id: 20, level: 'CE1', noun: 'voisins', options: ['nos', 'vos', 'leurs', 'le', 'la'], correct: ['nos', 'vos', 'leurs'] },
];

export const DET_ARTICLE_DATABASE: DetArticleSortTask[] = [
  { id: 1, level: 'CE2', article: 'le', type: 'défini' },
  { id: 2, level: 'CE2', article: 'la', type: 'défini' },
  { id: 3, level: 'CE2', article: 'les', type: 'défini' },
  { id: 4, level: 'CE2', article: "l'", type: 'défini' },
  { id: 5, level: 'CE2', article: 'un', type: 'indéfini' },
  { id: 6, level: 'CE2', article: 'une', type: 'indéfini' },
  { id: 7, level: 'CE2', article: 'des', type: 'indéfini' },
  { id: 8, level: 'CE2', article: 'le', type: 'défini' },
  { id: 9, level: 'CE2', article: 'un', type: 'indéfini' },
  { id: 10, level: 'CE2', article: 'la', type: 'défini' },
  { id: 11, level: 'CE2', article: 'une', type: 'indéfini' },
  { id: 12, level: 'CE2', article: 'les', type: 'défini' },
  { id: 13, level: 'CE2', article: 'des', type: 'indéfini' },
  { id: 14, level: 'CE2', article: "l'", type: 'défini' },
  { id: 15, level: 'CE2', article: 'le', type: 'défini' },
  { id: 16, level: 'CE2', article: 'une', type: 'indéfini' },
  { id: 17, level: 'CE2', article: 'des', type: 'indéfini' },
  { id: 18, level: 'CE2', article: 'la', type: 'défini' },
  { id: 19, level: 'CE2', article: 'un', type: 'indéfini' },
  { id: 20, level: 'CE2', article: 'les', type: 'défini' },
];
