
import { DictationTask } from '../types';

export const DICTATION_DATABASE: DictationTask[] = [
  // --- CE1 (50 phrases) ---
  { id: 1, level: 'CE1', sentence: "Le chat dort sur le tapis." },
  { id: 2, level: 'CE1', sentence: "La petite fille mange une pomme." },
  { id: 3, level: 'CE1', sentence: "Le chien court dans le jardin." },
  { id: 4, level: 'CE1', sentence: "Il fait beau aujourd'hui." },
  { id: 5, level: 'CE1', sentence: "Maman prépare un bon gâteau." },
  { id: 6, level: 'CE1', sentence: "Le cartable est très lourd." },
  { id: 7, level: 'CE1', sentence: "Les oiseaux chantent le matin." },
  { id: 8, level: 'CE1', sentence: "Je joue avec mon ballon rouge." },
  { id: 9, level: 'CE1', sentence: "La maîtresse écrit au tableau." },
  { id: 10, level: 'CE1', sentence: "Un gros lapin saute vite." },
  { id: 11, level: 'CE1', sentence: "Le bébé boit son lait." },
  { id: 12, level: 'CE1', sentence: "La porte de la classe est ouverte." },
  { id: 13, level: 'CE1', sentence: "Papa répare sa voiture bleue." },
  { id: 14, level: 'CE1', sentence: "Il y a des fleurs dans le vase." },
  { id: 15, level: 'CE1', sentence: "Le vent souffle dans les arbres." },
  { id: 16, level: 'CE1', sentence: "Nous allons à la piscine." },
  { id: 17, level: 'CE1', sentence: "Ma sœur a une jolie poupée." },
  { id: 18, level: 'CE1', sentence: "Le petit garçon est content." },
  { id: 19, level: 'CE1', sentence: "La pluie tombe sur le toit." },
  { id: 20, level: 'CE1', sentence: "Un oiseau vole très haut." },
  { id: 21, level: 'CE1', sentence: "Le loup a de grandes dents." },
  { id: 22, level: 'CE1', sentence: "Le soleil brille dans le ciel." },
  { id: 23, level: 'CE1', sentence: "J'ai perdu mon crayon gris." },
  { id: 24, level: 'CE1', sentence: "Le renard se cache dans le bois." },
  { id: 25, level: 'CE1', sentence: "La poule pond un bel œuf." },
  { id: 26, level: 'CE1', sentence: "Les élèves écoutent le maître." },
  { id: 27, level: 'CE1', sentence: "Le vélo de Lucas est neuf." },
  { id: 28, level: 'CE1', sentence: "Une baleine nage dans la mer." },
  { id: 29, level: 'CE1', sentence: "La soupe est bien chaude." },
  { id: 30, level: 'CE1', sentence: "Le clown fait rire les enfants." },
  { id: 31, level: 'CE1', sentence: "Il y a de la neige sur la montagne." },
  { id: 32, level: 'CE1', sentence: "Le singe mange une banane." },
  { id: 33, level: 'CE1', sentence: "Ma maison est au bout de la rue." },
  { id: 34, level: 'CE1', sentence: "Le poisson rouge tourne en rond." },
  { id: 35, level: 'CE1', sentence: "Je porte un bonnet en laine." },
  { id: 36, level: 'CE1', sentence: "La montre de Julie est cassée." },
  { id: 37, level: 'CE1', sentence: "L'avion décolle de la piste." },
  { id: 38, level: 'CE1', sentence: "Le lion est le roi de la forêt." },
  { id: 39, level: 'CE1', sentence: "Nous mangeons des fraises." },
  { id: 40, level: 'CE1', sentence: "Le livre est sur l'étagère." },
  { id: 41, level: 'CE1', sentence: "Mon frère a sept ans." },
  { id: 42, level: 'CE1', sentence: "Le fermier soigne ses vaches." },
  { id: 43, level: 'CE1', sentence: "La sorcière a un balai magique." },
  { id: 44, level: 'CE1', sentence: "Le train arrive en gare." },
  { id: 45, level: 'CE1', sentence: "Les vacances commencent bientôt." },
  { id: 46, level: 'CE1', sentence: "Je range mes jouets." },
  { id: 47, level: 'CE1', sentence: "La girafe a un long cou." },
  { id: 48, level: 'CE1', sentence: "Léo boit un jus d'orange." },
  { id: 49, level: 'CE1', sentence: "Le miroir est dans la chambre." },
  { id: 50, level: 'CE1', sentence: "Il faut se laver les mains." },

  // --- CE2 (50 phrases) ---
  { id: 51, level: 'CE2', sentence: "Les cerises sont mûres dans le verger." },
  { id: 52, level: 'CE2', sentence: "Le jeune garçon grimpe sur le grand chêne." },
  { id: 53, level: 'CE2', sentence: "Une grosse tempête approche de la côte." },
  { id: 54, level: 'CE2', sentence: "Nous avons acheté des légumes frais au marché." },
  { id: 55, level: 'CE2', sentence: "Le vent agite doucement les feuilles mortes." },
  { id: 56, level: 'CE2', sentence: "Les randonneurs marchent sur le petit sentier." },
  { id: 57, level: 'CE2', sentence: "La boulangère vend des croissants dorés." },
  { id: 58, level: 'CE2', sentence: "Le vieux château domine la vallée." },
  { id: 59, level: 'CE2', sentence: "Ma grand-mère raconte des histoires incroyables." },
  { id: 60, level: 'CE2', sentence: "Les enfants dessinent des animaux fantastiques." },
  { id: 61, level: 'CE2', sentence: "Il ne faut pas oublier ses affaires." },
  { id: 62, level: 'CE2', sentence: "Le ciel devient tout noir avant l'orage." },
  { id: 63, level: 'CE2', sentence: "Le renard roux surveille le poulailler." },
  { id: 64, level: 'CE2', sentence: "Cette année, nous partons à la montagne." },
  { id: 65, level: 'CE2', sentence: "Le facteur dépose les lettres dans la boîte." },
  { id: 66, level: 'CE2', sentence: "Les musiciens accordent leurs instruments." },
  { id: 67, level: 'CE2', sentence: "La mer est calme et bleue aujourd'hui." },
  { id: 68, level: 'CE2', sentence: "Une jolie mésange s'est posée sur le balcon." },
  { id: 69, level: 'CE2', sentence: "Le menuisier travaille le bois avec soin." },
  { id: 70, level: 'CE2', sentence: "Les cerfs-volants volent dans le ciel dégagé." },
  { id: 71, level: 'CE2', sentence: "La soupe au potiron est délicieuse." },
  { id: 72, level: 'CE2', sentence: "Il a plu toute la nuit sans s'arrêter." },
  { id: 73, level: 'CE2', sentence: "Les pompiers arrivent avec la grande échelle." },
  { id: 74, level: 'CE2', sentence: "Le petit déjeuner est prêt sur la table." },
  { id: 75, level: 'CE2', sentence: "Nous ramassons des coquillages sur la plage." },
  { id: 76, level: 'CE2', sentence: "L'ours blanc vit sur la banquise." },
  { id: 77, level: 'CE2', sentence: "La chèvre broute l'herbe du pré." },
  { id: 78, level: 'CE2', sentence: "Le magicien fait sortir un lapin de son chapeau." },
  { id: 79, level: 'CE2', sentence: "Les abeilles butinent les fleurs du jardin." },
  { id: 80, level: 'CE2', sentence: "Le policier siffle pour arrêter les voitures." },
  { id: 81, level: 'CE2', sentence: "Il faut toujours être poli avec les autres." },
  { id: 82, level: 'CE2', sentence: "La fourmi transporte une grosse miette." },
  { id: 83, level: 'CE2', sentence: "Le navire quitte le port ce soir." },
  { id: 84, level: 'CE2', sentence: "L'écureuil fait des provisions pour l'hiver." },
  { id: 85, level: 'CE2', sentence: "Les nuages cachent le sommet de la colline." },
  { id: 86, level: 'CE2', sentence: "La gazelle court très vite dans la savane." },
  { id: 87, level: 'CE2', sentence: "Le vieux livre a des pages jaunies." },
  { id: 88, level: 'CE2', sentence: "Nous avons vu des dauphins sauter dans les vagues." },
  { id: 89, level: 'CE2', sentence: "La cloche de l'église sonne midi." },
  { id: 90, level: 'CE2', sentence: "L'automne apporte de belles couleurs." },
  { id: 91, level: 'CE2', sentence: "Le skieur descend la piste enneigée." },
  { id: 92, level: 'CE2', sentence: "La lune éclaire la forêt silencieuse." },
  { id: 93, level: 'CE2', sentence: "Les paysans travaillent dur dans les champs." },
  { id: 94, level: 'CE2', sentence: "Le kangourou transporte son bébé dans sa poche." },
  { id: 95, level: 'CE2', sentence: "L'ordinateur est un outil très utile." },
  { id: 96, level: 'CE2', sentence: "La tortue avance lentement mais sûrement." },
  { id: 97, level: 'CE2', sentence: "Le jardinier arrose les salades." },
  { id: 98, level: 'CE2', sentence: "Le phare guide les bateaux pendant la nuit." },
  { id: 99, level: 'CE2', sentence: "Les enfants écoutent attentivement le conte." },
  { id: 100, level: 'CE2', sentence: "La fête foraine est arrivée en ville." },

  // --- CM1 (50 phrases) ---
  { id: 101, level: 'CM1', sentence: "L'astronome observe les étoiles avec son puissant télescope." },
  { id: 102, level: 'CM1', sentence: "Les explorateurs ont découvert une grotte mystérieuse au fond de la jungle." },
  { id: 103, level: 'CM1', sentence: "Il est important de respecter l'environnement pour protéger notre planète." },
  { id: 104, level: 'CM1', sentence: "Le sculpteur façonne patiemment la pierre pour créer une œuvre d'art." },
  { id: 105, level: 'CM1', sentence: "Les athlètes s'entraînent chaque jour pour participer à la compétition." },
  { id: 106, level: 'CM1', sentence: "La nouvelle bibliothèque propose de nombreux ouvrages passionnants." },
  { id: 107, level: 'CM1', sentence: "Le vent souffle violemment et secoue les volets de la vieille maison." },
  { id: 108, level: 'CM1', sentence: "Les archéologues ont trouvé des poteries anciennes dans le sable." },
  { id: 109, level: 'CM1', sentence: "Le cuisinier prépare une recette traditionnelle avec des produits locaux." },
  { id: 110, level: 'CM1', sentence: "Il faut toujours vérifier l'orthographe des mots difficiles." },
  { id: 111, level: 'CM1', sentence: "Les hirondelles reviennent au printemps pour construire leurs nids." },
  { id: 112, level: 'CM1', sentence: "Le photographe a capturé un moment magnifique dans la forêt." },
  { id: 113, level: 'CM1', sentence: "La science nous permet de comprendre le monde qui nous entoure." },
  { id: 114, level: 'CM1', sentence: "Les chevaliers portaient des armures en fer pendant les batailles." },
  { id: 115, level: 'CM1', sentence: "La musique adoucit les mœurs et procure beaucoup de plaisir." },
  { id: 116, level: 'CM1', sentence: "Les nuages s'accumulent et annoncent une averse imminente." },
  { id: 117, level: 'CM1', sentence: "L'ordinateur portable est devenu indispensable pour travailler." },
  { id: 118, level: 'CM1', sentence: "Le fleuve coule tranquillement vers l'océan infini." },
  { id: 119, level: 'CM1', sentence: "Les élèves écrivent un poème pour la fête des mères." },
  { id: 120, level: 'CM1', sentence: "Le garagiste change les pneus de mon véhicule." },
  { id: 121, level: 'CM1', sentence: "L'éléphant d'Afrique est le plus grand mammifère terrestre." },
  { id: 122, level: 'CM1', sentence: "Les alpinistes ont atteint le sommet après une ascension périlleuse." },
  { id: 123, level: 'CM1', sentence: "La lumière du phare balaie régulièrement la surface de l'eau." },
  { id: 124, level: 'CM1', sentence: "Le boulanger pétrit la pâte pour faire du pain croustillant." },
  { id: 125, level: 'CM1', sentence: "Nous devons économiser l'eau car elle est précieuse." },
  { id: 126, level: 'CM1', sentence: "Le loup hurle à la lune pendant les nuits d'hiver." },
  { id: 127, level: 'CM1', sentence: "Les couleurs de l'arc-en-ciel apparaissent après la pluie." },
  { id: 128, level: 'CM1', sentence: "Le vétérinaire soigne l'aile cassée du petit oiseau." },
  { id: 129, level: 'CM1', sentence: "La lecture est une aventure qui développe l'imaginaire." },
  { id: 130, level: 'CM1', sentence: "Les cerfs brament dans la forêt pendant la saison des amours." },
  { id: 131, level: 'CM1', sentence: "L'exposition au musée présente des tableaux de grands maîtres." },
  { id: 132, level: 'CM1', sentence: "Le climat change et nous devons adapter nos habitudes." },
  { id: 133, level: 'CM1', sentence: "La patience est une qualité nécessaire pour réussir ses projets." },
  { id: 134, level: 'CM1', sentence: "Les marins surveillent l'horizon pour apercevoir la terre ferme." },
  { id: 135, level: 'CM1', sentence: "L'abeille reine est protégée par toutes les ouvrières." },
  { id: 136, level: 'CM1', sentence: "Le pont traverse la rivière et relie les deux villages." },
  { id: 137, level: 'CM1', sentence: "La ponctuation est essentielle pour donner du sens à une phrase." },
  { id: 138, level: 'CM1', sentence: "Les sportifs respectent les règles pour jouer honnêtement." },
  { id: 139, level: 'CM1', sentence: "Le désert est un endroit aride où il pleut rarement." },
  { id: 140, level: 'CM1', sentence: "La découverte de l'Amérique a bouleversé l'histoire du monde." },
  { id: 141, level: 'CM1', sentence: "Le chocolat noir est souvent plus sain que le chocolat au lait." },
  { id: 142, level: 'CM1', sentence: "Les insectes jouent un rôle crucial dans la pollinisation." },
  { id: 143, level: 'CM1', sentence: "La foudre a frappé le vieux peuplier au milieu du champ." },
  { id: 144, level: 'CM1', sentence: "Le capitaine dirige son navire à travers la tempête." },
  { id: 145, level: 'CM1', sentence: "La solidarité est importante pour aider les personnes en difficulté." },
  { id: 146, level: 'CM1', sentence: "Le tigre chasse discrètement ses proies dans les herbes hautes." },
  { id: 147, level: 'CM1', sentence: "Les éoliennes produisent de l'énergie grâce à la force du vent." },
  { id: 148, level: 'CM1', sentence: "Le jardin zoologique accueille des espèces du monde entier." },
  { id: 149, level: 'CM1', sentence: "La créativité permet de trouver des solutions originales." },
  { id: 150, level: 'CM1', sentence: "Le voyageur contemple le paysage depuis le sommet de la colline." },

  // --- CM2 (50 phrases) ---
  { id: 151, level: 'CM2', sentence: "Les conséquences du réchauffement climatique sont visibles sur les glaciers." },
  { id: 152, level: 'CM2', sentence: "L'architecte conçoit des bâtiments modernes et respectueux de la nature." },
  { id: 153, level: 'CM2', sentence: "Il est primordial d'acquérir de solides connaissances dès le plus jeune âge." },
  { id: 154, level: 'CM2', sentence: "Les scientifiques étudient la biodiversité pour préserver les écosystèmes fragiles." },
  { id: 155, level: 'CM2', sentence: "La révolution industrielle a radicalement transformé le mode de vie des sociétés." },
  { id: 156, level: 'CM2', sentence: "Les spéléologues explorent les profondeurs de la Terre avec une grande prudence." },
  { id: 157, level: 'CM2', sentence: "La démocratie repose sur la participation active et libre des citoyens." },
  { id: 158, level: 'CM2', sentence: "Le développement durable est un enjeu majeur pour les générations futures." },
  { id: 159, level: 'CM2', sentence: "Les écrivains célèbres utilisent souvent des métaphores pour enrichir leurs textes." },
  { id: 160, level: 'CM2', sentence: "L'intelligence artificielle ouvre de nouvelles perspectives dans de nombreux domaines." },
  { id: 161, level: 'CM2', sentence: "La liberté d'expression est un droit fondamental dans notre société actuelle." },
  { id: 162, level: 'CM2', sentence: "Les astronomes ont identifié une nouvelle planète située hors de notre système." },
  { id: 163, level: 'CM2', sentence: "La maîtrise d'une langue étrangère est un atout considérable pour l'avenir." },
  { id: 164, level: 'CM2', sentence: "Les réformes économiques visent à améliorer le pouvoir d'achat des ménages." },
  { id: 165, level: 'CM2', sentence: "La pollution atmosphérique représente un danger sérieux pour la santé publique." },
  { id: 166, level: 'CM2', sentence: "Les nouvelles technologies ont modifié notre manière de communiquer quotidiennement." },
  { id: 167, level: 'CM2', sentence: "La conquête spatiale est une aventure extraordinaire qui fascine l'humanité." },
  { id: 168, level: 'CM2', sentence: "Les œuvres littéraires classiques sont encore étudiées avec intérêt aujourd'hui." },
  { id: 169, level: 'CM2', sentence: "La transition énergétique est nécessaire pour réduire nos émissions de carbone." },
  { id: 170, level: 'CM2', sentence: "Les droits de l'homme doivent être respectés partout dans le monde entier." },
  { id: 171, level: 'CM2', sentence: "La curiosité intellectuelle nous pousse à toujours apprendre de nouvelles choses." },
  { id: 172, level: 'CM2', sentence: "Les recherches médicales permettent de soigner des maladies autrefois incurables." },
  { id: 173, level: 'CM2', sentence: "La solidarité internationale est essentielle lors de catastrophes naturelles majeures." },
  { id: 174, level: 'CM2', sentence: "Les artistes contemporains explorent de nouvelles formes d'expression visuelle." },
  { id: 175, level: 'CM2', sentence: "La préservation des monuments historiques témoigne de notre passé culturel." },
  { id: 176, level: 'CM2', sentence: "Les énergies renouvelables sont une alternative durable aux combustibles fossiles." },
  { id: 177, level: 'CM2', sentence: "La rigueur scientifique est indispensable pour mener à bien une expérimentation." },
  { id: 178, level: 'CM2', sentence: "Les découvertes technologiques s'accélèrent et modifient notre environnement proche." },
  { id: 179, level: 'CM2', sentence: "La protection de la couche d'ozone est un succès de la coopération mondiale." },
  { id: 180, level: 'CM2', sentence: "Les grands explorateurs ont bravé l'inconnu pour découvrir de nouveaux horizons." },
  { id: 181, level: 'CM2', sentence: "La gestion des déchets est un défi quotidien pour les grandes agglomérations." },
  { id: 182, level: 'CM2', sentence: "L'accès à l'éducation est un levier puissant pour lutter contre la pauvreté." },
  { id: 183, level: 'CM2', sentence: "La justice sociale vise à réduire les inégalités entre les différents citoyens." },
  { id: 184, level: 'CM2', sentence: "Les échanges commerciaux internationaux favorisent la croissance de l'économie mondiale." },
  { id: 185, level: 'CM2', sentence: "La diplomatie permet de résoudre les conflits par le dialogue et la négociation." },
  { id: 186, level: 'CM2', sentence: "Les récits mythologiques expliquaient autrefois les phénomènes naturels inconnus." },
  { id: 187, level: 'CM2', sentence: "La nanotechnologie manipule la matière à une échelle extrêmement petite." },
  { id: 188, level: 'CM2', sentence: "Les parcs nationaux protègent les habitats naturels des espèces menacées." },
  { id: 189, level: 'CM2', sentence: "La liberté de la presse est une condition sine qua non de la démocratie." },
  { id: 190, level: 'CM2', sentence: "Les innovations numériques simplifient les démarches administratives de chacun." },
  { id: 191, level: 'CM2', sentence: "La compréhension du génome humain ouvre la voie à une médecine personnalisée." },
  { id: 192, level: 'CM2', sentence: "Les philosophes de l'Antiquité ont posé les bases de la pensée occidentale." },
  { id: 193, level: 'CM2', sentence: "La lutte contre le gaspillage alimentaire est une priorité environnementale." },
  { id: 194, level: 'CM2', sentence: "Les transports en commun sont une solution efficace pour réduire le trafic urbain." },
  { id: 195, level: 'CM2', sentence: "La tolérance et le respect sont les piliers d'une vie en communauté harmonieuse." },
  { id: 196, level: 'CM2', sentence: "Les courants marins jouent un rôle fondamental dans la régulation du climat." },
  { id: 197, level: 'CM2', sentence: "La transmission du savoir est le rôle essentiel des enseignants dévoués." },
  { id: 198, level: 'CM2', sentence: "Les infrastructures modernes facilitent le développement des régions isolées." },
  { id: 199, level: 'CM2', sentence: "La biodiversité marine est menacée par la pollution plastique des océans." },
  { id: 200, level: 'CM2', sentence: "Le patrimoine mondial de l'humanité regroupe des sites d'une valeur inestimable." },
];
