import { ShapeIdTask, PerimeterTask, ParallelTask } from '../types';

// ─── "Qui est-ce ?" ───────────────────────────────────────────────────────────
export const SHAPE_ID_DATABASE: ShapeIdTask[] = [
  // ── CE1 ──
  { id: 0, level: 'CE1', targetShape: 'carré',
    choices: [
      { shapeKey: 'square',    label: 'carré',     isCorrect: true  },
      { shapeKey: 'rectangle', label: 'rectangle', isCorrect: false },
      { shapeKey: 'triangle',  label: 'triangle',  isCorrect: false },
      { shapeKey: 'circle',    label: 'cercle',    isCorrect: false },
    ]},
  { id: 1, level: 'CE1', targetShape: 'rectangle',
    choices: [
      { shapeKey: 'rectangle', label: 'rectangle', isCorrect: true  },
      { shapeKey: 'square',    label: 'carré',     isCorrect: false },
      { shapeKey: 'triangle',  label: 'triangle',  isCorrect: false },
      { shapeKey: 'circle',    label: 'cercle',    isCorrect: false },
    ]},
  { id: 2, level: 'CE1', targetShape: 'triangle',
    choices: [
      { shapeKey: 'triangle',  label: 'triangle',  isCorrect: true  },
      { shapeKey: 'square',    label: 'carré',     isCorrect: false },
      { shapeKey: 'rectangle', label: 'rectangle', isCorrect: false },
      { shapeKey: 'circle',    label: 'cercle',    isCorrect: false },
    ]},
  { id: 3, level: 'CE1', targetShape: 'cercle',
    choices: [
      { shapeKey: 'circle',    label: 'cercle',    isCorrect: true  },
      { shapeKey: 'square',    label: 'carré',     isCorrect: false },
      { shapeKey: 'triangle',  label: 'triangle',  isCorrect: false },
      { shapeKey: 'rectangle', label: 'rectangle', isCorrect: false },
    ]},
  { id: 4, level: 'CE1', targetShape: 'carré',
    choices: [
      { shapeKey: 'square',    label: 'carré',     isCorrect: true  },
      { shapeKey: 'circle',    label: 'cercle',    isCorrect: false },
      { shapeKey: 'rectangle', label: 'rectangle', isCorrect: false },
      { shapeKey: 'triangle',  label: 'triangle',  isCorrect: false },
    ]},
  { id: 5, level: 'CE1', targetShape: 'triangle',
    choices: [
      { shapeKey: 'triangle',  label: 'triangle',  isCorrect: true  },
      { shapeKey: 'circle',    label: 'cercle',    isCorrect: false },
      { shapeKey: 'square',    label: 'carré',     isCorrect: false },
      { shapeKey: 'rectangle', label: 'rectangle', isCorrect: false },
    ]},
  { id: 6, level: 'CE1', targetShape: 'cercle',
    choices: [
      { shapeKey: 'circle',    label: 'cercle',    isCorrect: true  },
      { shapeKey: 'rectangle', label: 'rectangle', isCorrect: false },
      { shapeKey: 'square',    label: 'carré',     isCorrect: false },
      { shapeKey: 'triangle',  label: 'triangle',  isCorrect: false },
    ]},
  { id: 7, level: 'CE1', targetShape: 'rectangle',
    choices: [
      { shapeKey: 'rectangle', label: 'rectangle', isCorrect: true  },
      { shapeKey: 'triangle',  label: 'triangle',  isCorrect: false },
      { shapeKey: 'circle',    label: 'cercle',    isCorrect: false },
      { shapeKey: 'square',    label: 'carré',     isCorrect: false },
    ]},
  { id: 8, level: 'CE1', targetShape: 'carré',
    choices: [
      { shapeKey: 'square',    label: 'carré',     isCorrect: true  },
      { shapeKey: 'triangle',  label: 'triangle',  isCorrect: false },
      { shapeKey: 'circle',    label: 'cercle',    isCorrect: false },
      { shapeKey: 'rectangle', label: 'rectangle', isCorrect: false },
    ]},
  { id: 9, level: 'CE1', targetShape: 'triangle',
    choices: [
      { shapeKey: 'triangle',  label: 'triangle',  isCorrect: true  },
      { shapeKey: 'rectangle', label: 'rectangle', isCorrect: false },
      { shapeKey: 'circle',    label: 'cercle',    isCorrect: false },
      { shapeKey: 'square',    label: 'carré',     isCorrect: false },
    ]},
  // ── CE2 ──
  { id: 10, level: 'CE2', targetShape: 'losange',
    choices: [
      { shapeKey: 'rhombus',   label: 'losange',   isCorrect: true  },
      { shapeKey: 'square',    label: 'carré',     isCorrect: false },
      { shapeKey: 'trapezoid', label: 'trapèze',   isCorrect: false },
      { shapeKey: 'triangle',  label: 'triangle',  isCorrect: false },
    ]},
  { id: 11, level: 'CE2', targetShape: 'trapèze',
    choices: [
      { shapeKey: 'trapezoid', label: 'trapèze',   isCorrect: true  },
      { shapeKey: 'rhombus',   label: 'losange',   isCorrect: false },
      { shapeKey: 'rectangle', label: 'rectangle', isCorrect: false },
      { shapeKey: 'circle',    label: 'cercle',    isCorrect: false },
    ]},
  { id: 12, level: 'CE2', targetShape: 'losange',
    choices: [
      { shapeKey: 'rhombus',   label: 'losange',   isCorrect: true  },
      { shapeKey: 'rectangle', label: 'rectangle', isCorrect: false },
      { shapeKey: 'circle',    label: 'cercle',    isCorrect: false },
      { shapeKey: 'trapezoid', label: 'trapèze',   isCorrect: false },
    ]},
  { id: 13, level: 'CE2', targetShape: 'carré',
    choices: [
      { shapeKey: 'square',    label: 'carré',     isCorrect: true  },
      { shapeKey: 'rhombus',   label: 'losange',   isCorrect: false },
      { shapeKey: 'trapezoid', label: 'trapèze',   isCorrect: false },
      { shapeKey: 'triangle',  label: 'triangle',  isCorrect: false },
    ]},
  { id: 14, level: 'CE2', targetShape: 'trapèze',
    choices: [
      { shapeKey: 'trapezoid', label: 'trapèze',   isCorrect: true  },
      { shapeKey: 'square',    label: 'carré',     isCorrect: false },
      { shapeKey: 'rhombus',   label: 'losange',   isCorrect: false },
      { shapeKey: 'circle',    label: 'cercle',    isCorrect: false },
    ]},
  { id: 15, level: 'CE2', targetShape: 'rectangle',
    choices: [
      { shapeKey: 'rectangle', label: 'rectangle', isCorrect: true  },
      { shapeKey: 'rhombus',   label: 'losange',   isCorrect: false },
      { shapeKey: 'trapezoid', label: 'trapèze',   isCorrect: false },
      { shapeKey: 'triangle',  label: 'triangle',  isCorrect: false },
    ]},
  { id: 16, level: 'CE2', targetShape: 'cercle',
    choices: [
      { shapeKey: 'circle',    label: 'cercle',    isCorrect: true  },
      { shapeKey: 'rhombus',   label: 'losange',   isCorrect: false },
      { shapeKey: 'trapezoid', label: 'trapèze',   isCorrect: false },
      { shapeKey: 'square',    label: 'carré',     isCorrect: false },
    ]},
  { id: 17, level: 'CE2', targetShape: 'losange',
    choices: [
      { shapeKey: 'rhombus',   label: 'losange',   isCorrect: true  },
      { shapeKey: 'circle',    label: 'cercle',    isCorrect: false },
      { shapeKey: 'triangle',  label: 'triangle',  isCorrect: false },
      { shapeKey: 'rectangle', label: 'rectangle', isCorrect: false },
    ]},
  { id: 18, level: 'CE2', targetShape: 'triangle',
    choices: [
      { shapeKey: 'triangle',  label: 'triangle',  isCorrect: true  },
      { shapeKey: 'rhombus',   label: 'losange',   isCorrect: false },
      { shapeKey: 'trapezoid', label: 'trapèze',   isCorrect: false },
      { shapeKey: 'square',    label: 'carré',     isCorrect: false },
    ]},
  { id: 19, level: 'CE2', targetShape: 'trapèze',
    choices: [
      { shapeKey: 'trapezoid', label: 'trapèze',   isCorrect: true  },
      { shapeKey: 'triangle',  label: 'triangle',  isCorrect: false },
      { shapeKey: 'square',    label: 'carré',     isCorrect: false },
      { shapeKey: 'rhombus',   label: 'losange',   isCorrect: false },
    ]},
  // ── CM1 ──
  { id: 20, level: 'CM1', targetShape: 'parallélogramme',
    choices: [
      { shapeKey: 'parallelogram', label: 'parallélogramme', isCorrect: true  },
      { shapeKey: 'rhombus',       label: 'losange',         isCorrect: false },
      { shapeKey: 'trapezoid',     label: 'trapèze',         isCorrect: false },
      { shapeKey: 'pentagon',      label: 'pentagone',       isCorrect: false },
    ]},
  { id: 21, level: 'CM1', targetShape: 'pentagone',
    choices: [
      { shapeKey: 'pentagon',      label: 'pentagone',       isCorrect: true  },
      { shapeKey: 'parallelogram', label: 'parallélogramme', isCorrect: false },
      { shapeKey: 'rhombus',       label: 'losange',         isCorrect: false },
      { shapeKey: 'rectangle',     label: 'rectangle',       isCorrect: false },
    ]},
  { id: 22, level: 'CM1', targetShape: 'losange',
    choices: [
      { shapeKey: 'rhombus',       label: 'losange',         isCorrect: true  },
      { shapeKey: 'parallelogram', label: 'parallélogramme', isCorrect: false },
      { shapeKey: 'pentagon',      label: 'pentagone',       isCorrect: false },
      { shapeKey: 'square',        label: 'carré',           isCorrect: false },
    ]},
  { id: 23, level: 'CM1', targetShape: 'parallélogramme',
    choices: [
      { shapeKey: 'parallelogram', label: 'parallélogramme', isCorrect: true  },
      { shapeKey: 'rectangle',     label: 'rectangle',       isCorrect: false },
      { shapeKey: 'pentagon',      label: 'pentagone',       isCorrect: false },
      { shapeKey: 'trapezoid',     label: 'trapèze',         isCorrect: false },
    ]},
  { id: 24, level: 'CM1', targetShape: 'pentagone',
    choices: [
      { shapeKey: 'pentagon',      label: 'pentagone',       isCorrect: true  },
      { shapeKey: 'trapezoid',     label: 'trapèze',         isCorrect: false },
      { shapeKey: 'rhombus',       label: 'losange',         isCorrect: false },
      { shapeKey: 'circle',        label: 'cercle',          isCorrect: false },
    ]},
  { id: 25, level: 'CM1', targetShape: 'trapèze',
    choices: [
      { shapeKey: 'trapezoid',     label: 'trapèze',         isCorrect: true  },
      { shapeKey: 'parallelogram', label: 'parallélogramme', isCorrect: false },
      { shapeKey: 'pentagon',      label: 'pentagone',       isCorrect: false },
      { shapeKey: 'rhombus',       label: 'losange',         isCorrect: false },
    ]},
  { id: 26, level: 'CM1', targetShape: 'carré',
    choices: [
      { shapeKey: 'square',        label: 'carré',           isCorrect: true  },
      { shapeKey: 'parallelogram', label: 'parallélogramme', isCorrect: false },
      { shapeKey: 'pentagon',      label: 'pentagone',       isCorrect: false },
      { shapeKey: 'rhombus',       label: 'losange',         isCorrect: false },
    ]},
  { id: 27, level: 'CM1', targetShape: 'rectangle',
    choices: [
      { shapeKey: 'rectangle',     label: 'rectangle',       isCorrect: true  },
      { shapeKey: 'parallelogram', label: 'parallélogramme', isCorrect: false },
      { shapeKey: 'pentagon',      label: 'pentagone',       isCorrect: false },
      { shapeKey: 'trapezoid',     label: 'trapèze',         isCorrect: false },
    ]},
  { id: 28, level: 'CM1', targetShape: 'parallélogramme',
    choices: [
      { shapeKey: 'parallelogram', label: 'parallélogramme', isCorrect: true  },
      { shapeKey: 'square',        label: 'carré',           isCorrect: false },
      { shapeKey: 'triangle',      label: 'triangle',        isCorrect: false },
      { shapeKey: 'pentagon',      label: 'pentagone',       isCorrect: false },
    ]},
  { id: 29, level: 'CM1', targetShape: 'pentagone',
    choices: [
      { shapeKey: 'pentagon',      label: 'pentagone',       isCorrect: true  },
      { shapeKey: 'square',        label: 'carré',           isCorrect: false },
      { shapeKey: 'parallelogram', label: 'parallélogramme', isCorrect: false },
      { shapeKey: 'circle',        label: 'cercle',          isCorrect: false },
    ]},
  // ── CM2 ──
  { id: 30, level: 'CM2', targetShape: 'hexagone',
    choices: [
      { shapeKey: 'hexagon',       label: 'hexagone',        isCorrect: true  },
      { shapeKey: 'pentagon',      label: 'pentagone',       isCorrect: false },
      { shapeKey: 'octagon',       label: 'octogone',        isCorrect: false },
      { shapeKey: 'parallelogram', label: 'parallélogramme', isCorrect: false },
    ]},
  { id: 31, level: 'CM2', targetShape: 'octogone',
    choices: [
      { shapeKey: 'octagon',       label: 'octogone',        isCorrect: true  },
      { shapeKey: 'hexagon',       label: 'hexagone',        isCorrect: false },
      { shapeKey: 'pentagon',      label: 'pentagone',       isCorrect: false },
      { shapeKey: 'parallelogram', label: 'parallélogramme', isCorrect: false },
    ]},
  { id: 32, level: 'CM2', targetShape: 'parallélogramme',
    choices: [
      { shapeKey: 'parallelogram', label: 'parallélogramme', isCorrect: true  },
      { shapeKey: 'hexagon',       label: 'hexagone',        isCorrect: false },
      { shapeKey: 'octagon',       label: 'octogone',        isCorrect: false },
      { shapeKey: 'trapezoid',     label: 'trapèze',         isCorrect: false },
    ]},
  { id: 33, level: 'CM2', targetShape: 'hexagone',
    choices: [
      { shapeKey: 'hexagon',       label: 'hexagone',        isCorrect: true  },
      { shapeKey: 'octagon',       label: 'octogone',        isCorrect: false },
      { shapeKey: 'rhombus',       label: 'losange',         isCorrect: false },
      { shapeKey: 'pentagon',      label: 'pentagone',       isCorrect: false },
    ]},
  { id: 34, level: 'CM2', targetShape: 'octogone',
    choices: [
      { shapeKey: 'octagon',       label: 'octogone',        isCorrect: true  },
      { shapeKey: 'rhombus',       label: 'losange',         isCorrect: false },
      { shapeKey: 'hexagon',       label: 'hexagone',        isCorrect: false },
      { shapeKey: 'trapezoid',     label: 'trapèze',         isCorrect: false },
    ]},
  { id: 35, level: 'CM2', targetShape: 'losange',
    choices: [
      { shapeKey: 'rhombus',       label: 'losange',         isCorrect: true  },
      { shapeKey: 'hexagon',       label: 'hexagone',        isCorrect: false },
      { shapeKey: 'octagon',       label: 'octogone',        isCorrect: false },
      { shapeKey: 'parallelogram', label: 'parallélogramme', isCorrect: false },
    ]},
  { id: 36, level: 'CM2', targetShape: 'pentagone',
    choices: [
      { shapeKey: 'pentagon',      label: 'pentagone',       isCorrect: true  },
      { shapeKey: 'hexagon',       label: 'hexagone',        isCorrect: false },
      { shapeKey: 'octagon',       label: 'octogone',        isCorrect: false },
      { shapeKey: 'rhombus',       label: 'losange',         isCorrect: false },
    ]},
  { id: 37, level: 'CM2', targetShape: 'hexagone',
    choices: [
      { shapeKey: 'hexagon',       label: 'hexagone',        isCorrect: true  },
      { shapeKey: 'trapezoid',     label: 'trapèze',         isCorrect: false },
      { shapeKey: 'octagon',       label: 'octogone',        isCorrect: false },
      { shapeKey: 'square',        label: 'carré',           isCorrect: false },
    ]},
  { id: 38, level: 'CM2', targetShape: 'octogone',
    choices: [
      { shapeKey: 'octagon',       label: 'octogone',        isCorrect: true  },
      { shapeKey: 'pentagon',      label: 'pentagone',       isCorrect: false },
      { shapeKey: 'trapezoid',     label: 'trapèze',         isCorrect: false },
      { shapeKey: 'square',        label: 'carré',           isCorrect: false },
    ]},
  { id: 39, level: 'CM2', targetShape: 'parallélogramme',
    choices: [
      { shapeKey: 'parallelogram', label: 'parallélogramme', isCorrect: true  },
      { shapeKey: 'octagon',       label: 'octogone',        isCorrect: false },
      { shapeKey: 'hexagon',       label: 'hexagone',        isCorrect: false },
      { shapeKey: 'rhombus',       label: 'losange',         isCorrect: false },
    ]},
];

// ─── Calcule un périmètre ─────────────────────────────────────────────────────
export const PERIMETER_DATABASE: PerimeterTask[] = [
  { id: 0,  level: 'CE1', shapeKey: 'square',    sides: [5, 5, 5, 5],       answer: 20,  unit: 'cm' },
  { id: 1,  level: 'CE1', shapeKey: 'rectangle', sides: [8, 3, 8, 3],       answer: 22,  unit: 'cm' },
  { id: 2,  level: 'CE1', shapeKey: 'square',    sides: [4, 4, 4, 4],       answer: 16,  unit: 'cm' },
  { id: 3,  level: 'CE1', shapeKey: 'rectangle', sides: [6, 2, 6, 2],       answer: 16,  unit: 'cm' },
  { id: 4,  level: 'CE1', shapeKey: 'square',    sides: [7, 7, 7, 7],       answer: 28,  unit: 'cm' },
  { id: 5,  level: 'CE1', shapeKey: 'rectangle', sides: [10, 4, 10, 4],     answer: 28,  unit: 'cm' },
  { id: 6,  level: 'CE1', shapeKey: 'square',    sides: [3, 3, 3, 3],       answer: 12,  unit: 'cm' },
  { id: 7,  level: 'CE1', shapeKey: 'rectangle', sides: [9, 5, 9, 5],       answer: 28,  unit: 'cm' },
  { id: 8,  level: 'CE1', shapeKey: 'square',    sides: [6, 6, 6, 6],       answer: 24,  unit: 'cm' },
  { id: 9,  level: 'CE1', shapeKey: 'rectangle', sides: [12, 4, 12, 4],     answer: 32,  unit: 'cm' },
  { id: 10, level: 'CE1', shapeKey: 'square',    sides: [8, 8, 8, 8],       answer: 32,  unit: 'cm' },
  { id: 11, level: 'CE1', shapeKey: 'rectangle', sides: [15, 3, 15, 3],     answer: 36,  unit: 'cm' },
  { id: 12, level: 'CE2', shapeKey: 'square',    sides: [12, 12, 12, 12],   answer: 48,  unit: 'cm' },
  { id: 13, level: 'CE2', shapeKey: 'rectangle', sides: [15, 8, 15, 8],     answer: 46,  unit: 'cm' },
  { id: 14, level: 'CE2', shapeKey: 'triangle',  sides: [7, 7, 7],          answer: 21,  unit: 'cm' },
  { id: 15, level: 'CE2', shapeKey: 'triangle',  sides: [5, 8, 6],          answer: 19,  unit: 'cm' },
  { id: 16, level: 'CE2', shapeKey: 'square',    sides: [14, 14, 14, 14],   answer: 56,  unit: 'cm' },
  { id: 17, level: 'CE2', shapeKey: 'rectangle', sides: [20, 9, 20, 9],     answer: 58,  unit: 'cm' },
  { id: 18, level: 'CE2', shapeKey: 'triangle',  sides: [10, 10, 10],       answer: 30,  unit: 'cm' },
  { id: 19, level: 'CE2', shapeKey: 'triangle',  sides: [6, 9, 7],          answer: 22,  unit: 'cm' },
  { id: 20, level: 'CE2', shapeKey: 'square',    sides: [18, 18, 18, 18],   answer: 72,  unit: 'cm' },
  { id: 21, level: 'CE2', shapeKey: 'rectangle', sides: [25, 10, 25, 10],   answer: 70,  unit: 'cm' },
  { id: 22, level: 'CE2', shapeKey: 'triangle',  sides: [12, 8, 9],         answer: 29,  unit: 'cm' },
  { id: 23, level: 'CE2', shapeKey: 'triangle',  sides: [15, 15, 12],       answer: 42,  unit: 'cm' },
  { id: 24, level: 'CM1', shapeKey: 'square',    sides: [25, 25, 25, 25],   answer: 100, unit: 'cm' },
  { id: 25, level: 'CM1', shapeKey: 'rectangle', sides: [40, 15, 40, 15],   answer: 110, unit: 'cm' },
  { id: 26, level: 'CM1', shapeKey: 'triangle',  sides: [30, 40, 50],       answer: 120, unit: 'cm' },
  { id: 27, level: 'CM1', shapeKey: 'pentagon',  sides: [20, 20, 20, 20, 20], answer: 100, unit: 'cm' },
  { id: 28, level: 'CM1', shapeKey: 'square',    sides: [35, 35, 35, 35],   answer: 140, unit: 'cm' },
  { id: 29, level: 'CM1', shapeKey: 'rectangle', sides: [60, 20, 60, 20],   answer: 160, unit: 'cm' },
  { id: 30, level: 'CM1', shapeKey: 'triangle',  sides: [25, 35, 30],       answer: 90,  unit: 'cm' },
  { id: 31, level: 'CM1', shapeKey: 'pentagon',  sides: [15, 15, 15, 15, 15], answer: 75, unit: 'cm' },
  { id: 32, level: 'CM1', shapeKey: 'square',    sides: [45, 45, 45, 45],   answer: 180, unit: 'cm' },
  { id: 33, level: 'CM1', shapeKey: 'rectangle', sides: [50, 30, 50, 30],   answer: 160, unit: 'cm' },
  { id: 34, level: 'CM1', shapeKey: 'pentagon',  sides: [12, 12, 12, 12, 12], answer: 60, unit: 'cm' },
  { id: 35, level: 'CM1', shapeKey: 'triangle',  sides: [45, 55, 60],       answer: 160, unit: 'cm' },
  { id: 36, level: 'CM2', shapeKey: 'square',    sides: [4.5, 4.5, 4.5, 4.5],  answer: 18,   unit: 'cm' },
  { id: 37, level: 'CM2', shapeKey: 'rectangle', sides: [7.5, 3.5, 7.5, 3.5],  answer: 22,   unit: 'cm' },
  { id: 38, level: 'CM2', shapeKey: 'triangle',  sides: [5.5, 6.5, 4.5],       answer: 16.5, unit: 'cm' },
  { id: 39, level: 'CM2', shapeKey: 'pentagon',  sides: [3.5, 3.5, 3.5, 3.5, 3.5], answer: 17.5, unit: 'cm' },
  { id: 40, level: 'CM2', shapeKey: 'square',    sides: [6.5, 6.5, 6.5, 6.5],  answer: 26,   unit: 'cm' },
  { id: 41, level: 'CM2', shapeKey: 'rectangle', sides: [9.5, 4.5, 9.5, 4.5],  answer: 28,   unit: 'cm' },
  { id: 42, level: 'CM2', shapeKey: 'triangle',  sides: [8.5, 7.5, 6.5],       answer: 22.5, unit: 'cm' },
  { id: 43, level: 'CM2', shapeKey: 'pentagon',  sides: [5.5, 5.5, 5.5, 5.5, 5.5], answer: 27.5, unit: 'cm' },
  { id: 44, level: 'CM2', shapeKey: 'square',    sides: [8.5, 8.5, 8.5, 8.5],  answer: 34,   unit: 'cm' },
  { id: 45, level: 'CM2', shapeKey: 'rectangle', sides: [12.5, 5.5, 12.5, 5.5], answer: 36,  unit: 'cm' },
  { id: 46, level: 'CM2', shapeKey: 'triangle',  sides: [10.5, 9.5, 8.5],      answer: 28.5, unit: 'cm' },
  { id: 47, level: 'CM2', shapeKey: 'pentagon',  sides: [7.5, 7.5, 7.5, 7.5, 7.5], answer: 37.5, unit: 'cm' },
];

// ─── Parallèle ou perpendiculaire ? ──────────────────────────────────────────
export const PARALLEL_DATABASE: ParallelTask[] = [
  { id: 0,  level: 'CE1', lineA: { x1: 20, y1: 60,  x2: 280, y2: 60  }, lineB: { x1: 20, y1: 140, x2: 280, y2: 140 }, answer: 'parallel'      },
  { id: 1,  level: 'CE1', lineA: { x1: 150, y1: 10, x2: 150, y2: 190 }, lineB: { x1: 20, y1: 100, x2: 280, y2: 100 }, answer: 'perpendicular'  },
  { id: 2,  level: 'CE1', lineA: { x1: 20, y1: 80,  x2: 280, y2: 80  }, lineB: { x1: 20, y1: 160, x2: 280, y2: 160 }, answer: 'parallel'      },
  { id: 3,  level: 'CE1', lineA: { x1: 80,  y1: 10, x2: 80,  y2: 190 }, lineB: { x1: 20, y1: 100, x2: 280, y2: 100 }, answer: 'perpendicular'  },
  { id: 4,  level: 'CE1', lineA: { x1: 20, y1: 50,  x2: 280, y2: 50  }, lineB: { x1: 20, y1: 150, x2: 280, y2: 150 }, answer: 'parallel'      },
  { id: 5,  level: 'CE1', lineA: { x1: 200, y1: 10, x2: 200, y2: 190 }, lineB: { x1: 20, y1: 100, x2: 280, y2: 100 }, answer: 'perpendicular'  },
  { id: 6,  level: 'CE1', lineA: { x1: 20, y1: 70,  x2: 280, y2: 70  }, lineB: { x1: 20, y1: 130, x2: 280, y2: 130 }, answer: 'parallel'      },
  { id: 7,  level: 'CE1', lineA: { x1: 100, y1: 10, x2: 100, y2: 190 }, lineB: { x1: 20, y1: 100, x2: 280, y2: 100 }, answer: 'perpendicular'  },
  { id: 8,  level: 'CE1', lineA: { x1: 20, y1: 90,  x2: 280, y2: 90  }, lineB: { x1: 20, y1: 170, x2: 280, y2: 170 }, answer: 'parallel'      },
  { id: 9,  level: 'CE1', lineA: { x1: 120, y1: 10, x2: 120, y2: 190 }, lineB: { x1: 20, y1: 100, x2: 280, y2: 100 }, answer: 'perpendicular'  },
  { id: 10, level: 'CE2', lineA: { x1: 20, y1: 60,  x2: 280, y2: 60  }, lineB: { x1: 20, y1: 140, x2: 280, y2: 140 }, answer: 'parallel'      },
  { id: 11, level: 'CE2', lineA: { x1: 150, y1: 10, x2: 150, y2: 190 }, lineB: { x1: 20, y1: 100, x2: 280, y2: 100 }, answer: 'perpendicular'  },
  { id: 12, level: 'CE2', lineA: { x1: 20, y1: 40,  x2: 280, y2: 100 }, lineB: { x1: 20, y1: 120, x2: 280, y2: 180 }, answer: 'parallel'      },
  { id: 13, level: 'CE2', lineA: { x1: 20, y1: 20,  x2: 280, y2: 180 }, lineB: { x1: 20, y1: 180, x2: 280, y2: 20  }, answer: 'perpendicular'  },
  { id: 14, level: 'CE2', lineA: { x1: 20, y1: 30,  x2: 280, y2: 90  }, lineB: { x1: 20, y1: 100, x2: 280, y2: 190 }, answer: 'neither'       },
  { id: 15, level: 'CE2', lineA: { x1: 20, y1: 80,  x2: 280, y2: 80  }, lineB: { x1: 20, y1: 160, x2: 280, y2: 160 }, answer: 'parallel'      },
  { id: 16, level: 'CE2', lineA: { x1: 80,  y1: 10, x2: 80,  y2: 190 }, lineB: { x1: 20, y1: 100, x2: 280, y2: 100 }, answer: 'perpendicular'  },
  { id: 17, level: 'CE2', lineA: { x1: 20, y1: 50,  x2: 200, y2: 150 }, lineB: { x1: 20, y1: 120, x2: 280, y2: 80  }, answer: 'neither'       },
  { id: 18, level: 'CE2', lineA: { x1: 20, y1: 60,  x2: 280, y2: 120 }, lineB: { x1: 20, y1: 100, x2: 280, y2: 160 }, answer: 'parallel'      },
  { id: 19, level: 'CE2', lineA: { x1: 20, y1: 170, x2: 180, y2: 10  }, lineB: { x1: 20, y1: 60,  x2: 280, y2: 180 }, answer: 'neither'       },
  { id: 20, level: 'CM1', lineA: { x1: 20, y1: 50,  x2: 280, y2: 130 }, lineB: { x1: 20, y1: 100, x2: 280, y2: 180 }, answer: 'parallel'      },
  { id: 21, level: 'CM1', lineA: { x1: 20, y1: 20,  x2: 180, y2: 180 }, lineB: { x1: 20, y1: 180, x2: 180, y2: 20  }, answer: 'perpendicular'  },
  { id: 22, level: 'CM1', lineA: { x1: 20, y1: 40,  x2: 280, y2: 160 }, lineB: { x1: 20, y1: 80,  x2: 280, y2: 130 }, answer: 'neither'       },
  { id: 23, level: 'CM1', lineA: { x1: 20, y1: 70,  x2: 280, y2: 70  }, lineB: { x1: 20, y1: 140, x2: 280, y2: 140 }, answer: 'parallel'      },
  { id: 24, level: 'CM1', lineA: { x1: 60,  y1: 10, x2: 60,  y2: 190 }, lineB: { x1: 20, y1: 100, x2: 280, y2: 100 }, answer: 'perpendicular'  },
  { id: 25, level: 'CM1', lineA: { x1: 20, y1: 30,  x2: 280, y2: 170 }, lineB: { x1: 20, y1: 100, x2: 280, y2: 60  }, answer: 'neither'       },
  { id: 26, level: 'CM1', lineA: { x1: 20, y1: 60,  x2: 280, y2: 100 }, lineB: { x1: 20, y1: 120, x2: 280, y2: 160 }, answer: 'parallel'      },
  { id: 27, level: 'CM1', lineA: { x1: 20, y1: 30,  x2: 140, y2: 170 }, lineB: { x1: 60, y1: 170, x2: 200, y2: 30  }, answer: 'perpendicular'  },
  { id: 28, level: 'CM1', lineA: { x1: 20, y1: 150, x2: 280, y2: 50  }, lineB: { x1: 20, y1: 120, x2: 280, y2: 80  }, answer: 'neither'       },
  { id: 29, level: 'CM1', lineA: { x1: 20, y1: 80,  x2: 280, y2: 140 }, lineB: { x1: 20, y1: 40,  x2: 280, y2: 100 }, answer: 'parallel'      },
  { id: 30, level: 'CM2', lineA: { x1: 20, y1: 45,  x2: 280, y2: 115 }, lineB: { x1: 20, y1: 100, x2: 280, y2: 170 }, answer: 'parallel'      },
  { id: 31, level: 'CM2', lineA: { x1: 30, y1: 20,  x2: 100, y2: 180 }, lineB: { x1: 20, y1: 100, x2: 280, y2: 140 }, answer: 'neither'       },
  { id: 32, level: 'CM2', lineA: { x1: 20, y1: 30,  x2: 160, y2: 170 }, lineB: { x1: 60, y1: 170, x2: 200, y2: 30  }, answer: 'perpendicular'  },
  { id: 33, level: 'CM2', lineA: { x1: 20, y1: 60,  x2: 280, y2: 140 }, lineB: { x1: 20, y1: 80,  x2: 280, y2: 100 }, answer: 'neither'       },
  { id: 34, level: 'CM2', lineA: { x1: 20, y1: 55,  x2: 280, y2: 125 }, lineB: { x1: 20, y1: 105, x2: 280, y2: 175 }, answer: 'parallel'      },
  { id: 35, level: 'CM2', lineA: { x1: 20, y1: 170, x2: 180, y2: 30  }, lineB: { x1: 80, y1: 20,  x2: 220, y2: 180 }, answer: 'perpendicular'  },
  { id: 36, level: 'CM2', lineA: { x1: 20, y1: 40,  x2: 280, y2: 160 }, lineB: { x1: 20, y1: 90,  x2: 280, y2: 130 }, answer: 'neither'       },
  { id: 37, level: 'CM2', lineA: { x1: 20, y1: 70,  x2: 280, y2: 130 }, lineB: { x1: 20, y1: 110, x2: 280, y2: 170 }, answer: 'parallel'      },
  { id: 38, level: 'CM2', lineA: { x1: 20, y1: 25,  x2: 120, y2: 175 }, lineB: { x1: 20, y1: 175, x2: 280, y2: 105 }, answer: 'neither'       },
  { id: 39, level: 'CM2', lineA: { x1: 40, y1: 10,  x2: 40,  y2: 190 }, lineB: { x1: 20, y1: 100, x2: 280, y2: 100 }, answer: 'perpendicular'  },
];
