import { Level, PhraseTypeTask, PhrasePunctuationTask, PhraseOrderTask, PhraseValidTask } from '../types';

export const PHRASE_TYPE_DATABASE: PhraseTypeTask[] = [
  { id: 1, sentence: "Ce matin j'ai mangé une tartine avec du beurre.", type: "déclarative", level: "CE1" },
  { id: 2, sentence: "As-tu mangé ce matin ?", type: "interrogative", level: "CE1" },
  { id: 3, sentence: "Ramasse ton bol !", type: "impérative", level: "CE1" },
  { id: 4, sentence: "Le chat dort sur le canapé.", type: "déclarative", level: "CE1" },
  { id: 5, sentence: "Ferme la porte s'il te plaît !", type: "impérative", level: "CE1" },
  { id: 6, sentence: "Est-ce que tu aimes le chocolat ?", type: "interrogative", level: "CE1" },
  { id: 7, sentence: "Les enfants jouent dans la cour.", type: "déclarative", level: "CE1" },
  { id: 8, sentence: "Range ta chambre !", type: "impérative", level: "CE1" },
  { id: 9, sentence: "Où habites-tu ?", type: "interrogative", level: "CE1" },
  { id: 10, sentence: "Il fait beau aujourd'hui.", type: "déclarative", level: "CE1" },
  { id: 11, sentence: "Viens manger !", type: "impérative", level: "CE1" },
  { id: 12, sentence: "Quel est ton animal préféré ?", type: "interrogative", level: "CE1" },
  { id: 13, sentence: "Ma sœur lit un livre.", type: "déclarative", level: "CE2" },
  { id: 14, sentence: "Ne cours pas dans les couloirs !", type: "impérative", level: "CE2" },
  { id: 15, sentence: "Pourquoi pleure-t-il ?", type: "interrogative", level: "CE2" },
  { id: 16, sentence: "Nous partons en vacances demain.", type: "déclarative", level: "CE2" },
  { id: 17, sentence: "Faites vos devoirs avant de jouer !", type: "impérative", level: "CE2" },
  { id: 18, sentence: "Quand arriveras-tu ?", type: "interrogative", level: "CE2" },
  { id: 19, sentence: "Le soleil se lève à l'est.", type: "déclarative", level: "CE2" },
  { id: 20, sentence: "Pensez à éteindre la lumière !", type: "impérative", level: "CE2" },
];

export const PHRASE_PUNCTUATION_DATABASE: PhrasePunctuationTask[] = [
  { id: 1, sentence: "Ce matin j'ai mangé une tartine avec du beurre", answer: ".", level: "CE1" },
  { id: 2, sentence: "As-tu mangé ce matin", answer: "?", level: "CE1" },
  { id: 3, sentence: "Ramasse ton bol", answer: "!", level: "CE1" },
  { id: 4, sentence: "Le chat dort sur le canapé", answer: ".", level: "CE1" },
  { id: 5, sentence: "Ferme la porte s'il te plaît", answer: "!", level: "CE1" },
  { id: 6, sentence: "Est-ce que tu aimes le chocolat", answer: "?", level: "CE1" },
  { id: 7, sentence: "Les enfants jouent dans la cour", answer: ".", level: "CE1" },
  { id: 8, sentence: "Range ta chambre", answer: "!", level: "CE1" },
  { id: 9, sentence: "Où habites-tu", answer: "?", level: "CE1" },
  { id: 10, sentence: "Il fait beau aujourd'hui", answer: ".", level: "CE1" },
  { id: 11, sentence: "Viens manger", answer: "!", level: "CE1" },
  { id: 12, sentence: "Quel est ton animal préféré", answer: "?", level: "CE1" },
  { id: 13, sentence: "Nous partons en vacances demain", answer: ".", level: "CE2" },
  { id: 14, sentence: "Ne cours pas dans les couloirs", answer: "!", level: "CE2" },
  { id: 15, sentence: "Pourquoi pleure-t-il", answer: "?", level: "CE2" },
  { id: 16, sentence: "Le soleil se lève à l'est", answer: ".", level: "CE2" },
  { id: 17, sentence: "Faites vos devoirs avant de jouer", answer: "!", level: "CE2" },
  { id: 18, sentence: "Quand arriveras-tu", answer: "?", level: "CE2" },
  { id: 19, sentence: "Ma sœur lit un livre passionnant", answer: ".", level: "CE2" },
  { id: 20, sentence: "Pensez à éteindre la lumière", answer: "!", level: "CE2" },
];

export const PHRASE_ORDER_DATABASE: PhraseOrderTask[] = [
  { id: 1, words: ["Le", "chat", "dort", "sur", "le", "canapé."], level: "CE1" },
  { id: 2, words: ["Les", "enfants", "jouent", "dans", "la", "cour."], level: "CE1" },
  { id: 3, words: ["Je", "mange", "une", "pomme", "rouge."], level: "CE1" },
  { id: 4, words: ["Ma", "mère", "prépare", "le", "dîner."], level: "CE1" },
  { id: 5, words: ["Le", "chien", "court", "dans", "le", "jardin."], level: "CE1" },
  { id: 6, words: ["Nous", "partons", "en", "vacances", "demain."], level: "CE1" },
  { id: 7, words: ["Elle", "lit", "un", "livre", "intéressant."], level: "CE2" },
  { id: 8, words: ["Mon", "frère", "fait", "ses", "devoirs."], level: "CE1" },
  { id: 9, words: ["Les", "oiseaux", "chantent", "le", "matin."], level: "CE1" },
  { id: 10, words: ["Il", "pleut", "très", "fort", "aujourd'hui."], level: "CE2" },
  { id: 11, words: ["La", "maîtresse", "explique", "la", "leçon."], level: "CE2" },
  { id: 12, words: ["Nous", "regardons", "un", "film", "ce", "soir."], level: "CE2" },
  { id: 13, words: ["Le", "soleil", "brille", "dans", "le", "ciel."], level: "CE1" },
  { id: 14, words: ["Papa", "conduit", "la", "voiture", "doucement."], level: "CE2" },
  { id: 15, words: ["Les", "fleurs", "poussent", "au", "printemps."], level: "CE2" },
];

export const PHRASE_VALID_DATABASE: PhraseValidTask[] = [
  { id: 1, sentence: "Le chat dort sur le canapé.", isValid: true, reason: "", level: "CE1" },
  { id: 2, sentence: "le chien court dans le jardin.", isValid: false, reason: "Pas de majuscule au début", level: "CE1" },
  { id: 3, sentence: "Les enfants jouent", isValid: false, reason: "Pas de ponctuation finale", level: "CE1" },
  { id: 4, sentence: "Je mange une pomme rouge.", isValid: true, reason: "", level: "CE1" },
  { id: 5, sentence: "Mange le nuage la table.", isValid: false, reason: "Phrase sans sens", level: "CE1" },
  { id: 6, sentence: "Ma mère prépare le dîner.", isValid: true, reason: "", level: "CE1" },
  { id: 7, sentence: "le soleil brille dans le ciel", isValid: false, reason: "Pas de majuscule, pas de point", level: "CE1" },
  { id: 8, sentence: "Nous partons en vacances demain.", isValid: true, reason: "", level: "CE2" },
  { id: 9, sentence: "Courent vite les enfants.", isValid: false, reason: "Ordre des mots incorrect", level: "CE2" },
  { id: 10, sentence: "Elle lit un livre intéressant.", isValid: true, reason: "", level: "CE2" },
  { id: 11, sentence: "saute la lune sur.", isValid: false, reason: "Phrase sans sens et sans majuscule", level: "CE1" },
  { id: 12, sentence: "Les fleurs poussent au printemps.", isValid: true, reason: "", level: "CE1" },
  { id: 13, sentence: "Mon frère fait ses devoirs!", isValid: true, reason: "", level: "CE2" },
  { id: 14, sentence: "papa conduit la voiture doucement.", isValid: false, reason: "Pas de majuscule au début", level: "CE2" },
  { id: 15, sentence: "Les oiseaux chantent le matin.", isValid: true, reason: "", level: "CE1" },
  { id: 16, sentence: "Le livre mange la chaise bleue.", isValid: false, reason: "Phrase sans sens", level: "CE2" },
  { id: 17, sentence: "Il pleut très fort aujourd'hui.", isValid: true, reason: "", level: "CE2" },
  { id: 18, sentence: "joue dans la cour les enfants", isValid: false, reason: "Pas de majuscule et ordre incorrect", level: "CE2" },
  { id: 19, sentence: "La maîtresse explique la leçon.", isValid: true, reason: "", level: "CE2" },
  { id: 20, sentence: "Nous regardons un film ce soir.", isValid: true, reason: "", level: "CE1" },
];
