import { SilentLetterTask, SpellingChoiceTask } from '../types';

export const SILENT_LETTER_DATABASE: SilentLetterTask[] = [
  { id: 1, hint: "un arbre fruitier", partialWord: "frui…", answer: "t", options: ["t", "s", "d", "x"], level: "CE1" },
  { id: 2, hint: "du laitage", partialWord: "lai…", answer: "t", options: ["t", "s", "p", "d"], level: "CE1" },
  { id: 3, hint: "un noiselier", partialWord: "noi…", answer: "x", options: ["x", "s", "t", "d"], level: "CE1" },
  { id: 4, hint: "une boulangerie", partialWord: "bou…", answer: "d", options: ["d", "t", "s", "x"], level: "CE1" },
  { id: 5, hint: "une charpentière", partialWord: "charpen…", answer: "t", options: ["t", "s", "d", "r"], level: "CE2" },
  { id: 6, hint: "un jardinier", partialWord: "jar…", answer: "d", options: ["d", "t", "s", "x"], level: "CE1" },
  { id: 7, hint: "une plombière (glace)", partialWord: "plom…", answer: "b", options: ["b", "t", "s", "d"], level: "CE2" },
  { id: 8, hint: "un gantelet", partialWord: "gan…", answer: "t", options: ["t", "s", "d", "x"], level: "CE2" },
  { id: 9, hint: "un caneton", partialWord: "cane…", answer: "t", options: ["t", "s", "d", "x"], level: "CE1" },
  { id: 10, hint: "une souricière", partialWord: "souri…", answer: "s", options: ["s", "t", "d", "x"], level: "CE2" },
  { id: 11, hint: "une noisette", partialWord: "noi…", answer: "x", options: ["x", "s", "t", "d"], level: "CE1" },
  { id: 12, hint: "un corpulent", partialWord: "cor…", answer: "p", options: ["p", "t", "s", "d"], level: "CE2" },
  { id: 13, hint: "une vinaigrette", partialWord: "vinai…", answer: "g", options: ["g", "t", "s", "d"], level: "CE2" },
  { id: 14, hint: "un bouquet", partialWord: "bou…", answer: "t", options: ["t", "s", "d", "x"], level: "CE2" },
  { id: 15, hint: "une chatière", partialWord: "cha…", answer: "t", options: ["t", "s", "d", "x"], level: "CE1" },
  { id: 16, hint: "un sanguin", partialWord: "san…", answer: "g", options: ["g", "t", "s", "d"], level: "CE2" },
  { id: 17, hint: "la verdure", partialWord: "ver…", answer: "d", options: ["d", "t", "s", "x"], level: "CE1" },
  { id: 18, hint: "une corderie", partialWord: "cor…", answer: "d", options: ["d", "t", "s", "x"], level: "CE2" },
  { id: 19, hint: "un robinet", partialWord: "robi…", answer: "n", options: ["n", "t", "s", "d"], level: "CE1" },
  { id: 20, hint: "un longtemps", partialWord: "lon…", answer: "g", options: ["g", "t", "s", "d"], level: "CE2" },
];

export const SPELLING_CHOICE_DATABASE: SpellingChoiceTask[] = [
  // s ou ss
  { id: 1, textBefore: "du rai", textAfter: "in", answer: "s", options: ["s", "ss"], rule: "ortho-s-ss", level: "CE1" },
  { id: 2, textBefore: "au", textAfter: "i", answer: "ss", options: ["s", "ss"], rule: "ortho-s-ss", level: "CE1" },
  { id: 3, textBefore: "la pâti", textAfter: "erie", answer: "ss", options: ["s", "ss"], rule: "ortho-s-ss", level: "CE1" },
  { id: 4, textBefore: "la poi", textAfter: "on", answer: "s", options: ["s", "ss"], rule: "ortho-s-ss", level: "CE1" },
  { id: 5, textBefore: "la mai", textAfter: "on", answer: "s", options: ["s", "ss"], rule: "ortho-s-ss", level: "CE1" },
  { id: 6, textBefore: "le poi", textAfter: "on", answer: "ss", options: ["s", "ss"], rule: "ortho-s-ss", level: "CE1" },
  { id: 7, textBefore: "la trou", textAfter: "e", answer: "ss", options: ["s", "ss"], rule: "ortho-s-ss", level: "CE1" },
  { id: 8, textBefore: "une bli", textAfter: "ure", answer: "ss", options: ["s", "ss"], rule: "ortho-s-ss", level: "CE2" },
  { id: 9, textBefore: "la vi", textAfter: "ite", answer: "s", options: ["s", "ss"], rule: "ortho-s-ss", level: "CE1" },
  { id: 10, textBefore: "dé", textAfter: "ert", answer: "ss", options: ["s", "ss"], rule: "ortho-s-ss", level: "CE2" },
  { id: 11, textBefore: "le mu", textAfter: "ée", answer: "s", options: ["s", "ss"], rule: "ortho-s-ss", level: "CE1" },
  { id: 12, textBefore: "la va", textAfter: "e", answer: "ss", options: ["s", "ss"], rule: "ortho-s-ss", level: "CE2" },

  // n ou m devant m, b, p
  { id: 13, textBefore: "mai", textAfter: "tenant", answer: "n", options: ["n", "m"], rule: "ortho-n-m", level: "CE1" },
  { id: 14, textBefore: "la ca", textAfter: "pagne", answer: "m", options: ["n", "m"], rule: "ortho-n-m", level: "CE1" },
  { id: 15, textBefore: "cha", textAfter: "ter", answer: "n", options: ["n", "m"], rule: "ortho-n-m", level: "CE1" },
  { id: 16, textBefore: "un ti", textAfter: "bre", answer: "m", options: ["n", "m"], rule: "ortho-n-m", level: "CE1" },
  { id: 17, textBefore: "la ja", textAfter: "be", answer: "m", options: ["n", "m"], rule: "ortho-n-m", level: "CE1" },
  { id: 18, textBefore: "une bo", textAfter: "be", answer: "m", options: ["n", "m"], rule: "ortho-n-m", level: "CE1" },
  { id: 19, textBefore: "la cho", textAfter: "pier", answer: "m", options: ["n", "m"], rule: "ortho-n-m", level: "CE2" },
  { id: 20, textBefore: "so", textAfter: "bre", answer: "m", options: ["n", "m"], rule: "ortho-n-m", level: "CE2" },
  { id: 21, textBefore: "l'a", textAfter: "bassadeur", answer: "m", options: ["n", "m"], rule: "ortho-n-m", level: "CE2" },
  { id: 22, textBefore: "gra", textAfter: "d", answer: "n", options: ["n", "m"], rule: "ortho-n-m", level: "CE1" },
  { id: 23, textBefore: "une la", textAfter: "pe", answer: "m", options: ["n", "m"], rule: "ortho-n-m", level: "CE1" },
  { id: 24, textBefore: "une tro", textAfter: "pette", answer: "m", options: ["n", "m"], rule: "ortho-n-m", level: "CE2" },

  // c ou ç
  { id: 25, textBefore: "le gar", textAfter: "on", answer: "ç", options: ["c", "ç"], rule: "ortho-c-cedilla", level: "CE1" },
  { id: 26, textBefore: "la le", textAfter: "on", answer: "ç", options: ["c", "ç"], rule: "ortho-c-cedilla", level: "CE1" },
  { id: 27, textBefore: "", textAfter: "ela", answer: "c", options: ["c", "ç"], rule: "ortho-c-cedilla", level: "CE1" },
  { id: 28, textBefore: "", textAfter: "ouper", answer: "c", options: ["c", "ç"], rule: "ortho-c-cedilla", level: "CE1" },
  { id: 29, textBefore: "un bra", textAfter: "elet", answer: "c", options: ["c", "ç"], rule: "ortho-c-cedilla", level: "CE2" },
  { id: 30, textBefore: "une balan", textAfter: "oire", answer: "ç", options: ["c", "ç"], rule: "ortho-c-cedilla", level: "CE1" },
  { id: 31, textBefore: "la dé", textAfter: "ision", answer: "c", options: ["c", "ç"], rule: "ortho-c-cedilla", level: "CE2" },
  { id: 32, textBefore: "un dé", textAfter: "oupage", answer: "c", options: ["c", "ç"], rule: "ortho-c-cedilla", level: "CE1" },
  { id: 33, textBefore: "du su", textAfter: "re", answer: "ç", options: ["c", "ç"], rule: "ortho-c-cedilla", level: "CE2" },
  { id: 34, textBefore: "la fa", textAfter: "ade", answer: "ç", options: ["c", "ç"], rule: "ortho-c-cedilla", level: "CE2" },

  // g ou ge
  { id: 35, textBefore: "nous man", textAfter: "ons", answer: "ge", options: ["g", "ge"], rule: "ortho-g-ge", level: "CE1" },
  { id: 36, textBefore: "il na", textAfter: "ait", answer: "ge", options: ["g", "ge"], rule: "ortho-g-ge", level: "CE2" },
  { id: 37, textBefore: "un pi", textAfter: "on", answer: "ge", options: ["g", "ge"], rule: "ortho-g-ge", level: "CE1" },
  { id: 38, textBefore: "un re", textAfter: "ard", answer: "g", options: ["g", "ge"], rule: "ortho-g-ge", level: "CE1" },
  { id: 39, textBefore: "une ", textAfter: "affe", answer: "g", options: ["g", "ge"], rule: "ortho-g-ge", level: "CE1" },
  { id: 40, textBefore: "nous jou", textAfter: "ons", answer: "ge", options: ["g", "ge"], rule: "ortho-g-ge", level: "CE2" },
  { id: 41, textBefore: "un bour", textAfter: "on", answer: "ge", options: ["g", "ge"], rule: "ortho-g-ge", level: "CE2" },
  { id: 42, textBefore: "nous plon", textAfter: "ons", answer: "ge", options: ["g", "ge"], rule: "ortho-g-ge", level: "CE2" },
  { id: 43, textBefore: "un ", textAfter: "âteau", answer: "g", options: ["g", "ge"], rule: "ortho-g-ge", level: "CE1" },
  { id: 44, textBefore: "la na", textAfter: "eoire", answer: "ge", options: ["g", "ge"], rule: "ortho-g-ge", level: "CE2" },

  // g ou gu
  { id: 45, textBefore: "une ", textAfter: "itare", answer: "gu", options: ["g", "gu"], rule: "ortho-g-gu", level: "CE1" },
  { id: 46, textBefore: "lon", textAfter: "e", answer: "gu", options: ["g", "gu"], rule: "ortho-g-gu", level: "CE1" },
  { id: 47, textBefore: "une ", textAfter: "enouille", answer: "gu", options: ["g", "gu"], rule: "ortho-g-gu", level: "CE1" },
  { id: 48, textBefore: "un ", textAfter: "arçon", answer: "g", options: ["g", "gu"], rule: "ortho-g-gu", level: "CE1" },
  { id: 49, textBefore: "la ", textAfter: "erre", answer: "gu", options: ["g", "gu"], rule: "ortho-g-gu", level: "CE1" },
  { id: 50, textBefore: "une ", textAfter: "irlande", answer: "gu", options: ["g", "gu"], rule: "ortho-g-gu", level: "CE2" },
  { id: 51, textBefore: "un ", textAfter: "âteau", answer: "g", options: ["g", "gu"], rule: "ortho-g-gu", level: "CE1" },
  { id: 52, textBefore: "la bla", textAfter: "e", answer: "gu", options: ["g", "gu"], rule: "ortho-g-gu", level: "CE2" },
  { id: 53, textBefore: "blo", textAfter: "er", answer: "gu", options: ["g", "gu"], rule: "ortho-g-gu", level: "CE2" },
  { id: 54, textBefore: "un bo", textAfter: "et", answer: "gu", options: ["g", "gu"], rule: "ortho-g-gu", level: "CE2" },
];
